### ISSUE TITLE
SQL Query Error. [1364] Field 'money' doesn't have a default value

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#10]
SQL Query Error. [1364] Field 'money' doesn't have a default value

**Comment by TheDoctor0** [comment]
Are you trying to manually insert records into csgo_data table?
This error normally does not happen as all values are populated in load_data_handle function.

**Comment by ksm200** [comment]
no and loading the mod itself

**Comment by NoahLTU** [comment]
Well everything should work if you installed mod correctly

**Comment by TheDoctor0** [comment]
I would say that is really weird, because at no point in the plugin money field is being inserted/updated with null value.
I'll add explicit default value (0) to this column for full compatibility, but in normal circumstances it should not be required.

**Comment by ksm200** [comment]
Ok thanks
