### ISSUE TITLE
csgo_min_players Dont work

### ISSUE THREAD

**Issue by popilas** [TheDoctor0/CSGOMod#104]
Hello first sorry for the closed topic.
I got problem when i do csgo_core.sma
bind_pcvar_num(create_cvar("csgo_min_players", "4"), minPlayers);
and restart server still not working. the player on the server is one and when plant/defuse bomb or take hostage he got reward
which is specified in csgo_mod.cfg

I also tried to add cvar ir csgo_mod.cfg with line
csgo_min_player_filter "4" but still not working. Thanks!

**Comment by regener** [comment]
What mod version are you using? It works well for me.
Also you have to edit it only in the csgo_mod.cfg, nithing else to do.

**Comment by popilas** [comment]
![csgominpay](https://user-images.githubusercontent.com/74811825/103416902-4b43ae80-4b91-11eb-8f7d-50a23e674964.png)

[CS:GO] You got 0.12 Euro for planting the bomb.
[CS:GO] You got 0.12 Euro for winning the round.
version 2.4.0

**Comment by regener** [comment]
You are changing the wrong cvar. The first is the player number, the second is the filtering method.
https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/configs/csgo_mod.cfg#L49-L61

**Comment by popilas** [comment]
> popilas
> You are changing the wrong cvar. The first is the player number, the second is the filtering method.
> https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/configs/csgo_mod.cfg#L49-L61

You mean csgo_min_player_filter "0" ?
Dont worked
