### ISSUE TITLE
m3 error

### ISSUE THREAD

**Issue by tenlimba** [TheDoctor0/CSGOMod#105]
when you take m3 pica the server at the moment is the only weapon I've discovered that does that.

**Comment by popilas** [comment]
> when you take m3 pica the server at the moment is the only weapon I've discovered that does that.


I don't understand what you want to say

**Comment by tenlimba** [comment]
When you take the m3 weapon from the ground, the server drops, but only at m3 did I notice

**Comment by popilas** [comment]
Try delete from unprecacher
list.ini

models/v_m3.mdl c models/csgo_v2_default/m3/v_m3.mdl

**Comment by tenlimba** [comment]
I solved with this https://github.com/TheDoctor0/CSGOMod/commit/d5bcd1e18589d998e58710a8b906203fa881935c
