### ISSUE TITLE
skins problems

### ISSUE THREAD

**Issue by popilas** [TheDoctor0/CSGOMod#106]
![bug2](https://user-images.githubusercontent.com/74811825/103483093-9ce87500-4ded-11eb-9ccc-fe0ceec0a374.png)
Menu price is
when to confirm price is good
When has more than 1 showing (7)

And this:

; Skin rarity can be:
; 1 - Common
; 2 - Uncommon
; 3 - Rare
; 4 - Mythical
; 5 - Legendary
; 6 - Ancient
; 7 - Exceedingly Rare (only knives)
; 8 - Immortal (cannot be bought or aquired by draw)

does not work I mean skin rarity

"Bayonet | Black Laminate"    "models/ozone/knife/v_bayoblacklaminate.mdl"           "1" "350"  "8"
"Bayonet | Lore"              "models/ozone/knife/v_bayonetlore.mdl"                 "2" "375"  "8"
"Bayonet | Ultravoilet"       "models/ozone/knife/v_bayoultraviolet.mdl"             "3" "400"  "8"

**Comment by TheDoctor0** [comment]
There are two skins prices:
1. Drawing skin.
2. Buying skin.
On your screenshots, you mixed up those two things.

`(7)` is a rarity - Exceedingly Rare

When having multiple skins there is additional information:
![20210103171404_1](https://user-images.githubusercontent.com/16612504/103483369-1f216b00-4de7-11eb-9693-8cc686ad99c4.jpg)

> does not work I mean skin rarity

Skin rarity "Exceedingly Rare" is forced for knives, but an idea to allow also "Immortal" seems good to me.

**Comment by popilas** [comment]
https://www30.zippyshare.com/v/9CqSsmb7/file.html

**Comment by popilas** [comment]
I mean all knifes skins price is 75euro, when i pressed on skin its show good price. See vid .pls.
