### ISSUE TITLE
skins

### ISSUE THREAD

**Issue by popilas** [TheDoctor0/CSGOMod#108]
Sorry for that but. 2.5.2
![desrakurva](https://user-images.githubusercontent.com/74811825/103526665-ebe3e800-4e89-11eb-9cb2-09b833869049.png)

Maybe you can add to 1.4 version multi lang? I think 1.4 is best and no bugs

**Comment by TheDoctor0** [comment]
I barely have any time to support this mod, so no, I will not add multilang to version 1.4.
If you want, you can do it yourself.

**Comment by popilas** [comment]
okey.
This is skins or .txt problem with marking ? I mean pictures problem

**Comment by TheDoctor0** [comment]
It was an issue with `Extend management of knife and m4a4 skins (separate menus and draw price).` changes from yesterday. Fix has been applied only to the core plugin.

**Comment by fl0werD** [comment]
> I barely have any time to support this mod, so no, I will not add multilang to version 1.4.
> If you want, you can do it yourself.

It's few lines of code.

**Comment by TheDoctor0** [comment]
> It's few lines of code.

Have you even seen the source code for version 1.4? It took me nearly a month to add multilang support while working on version 2.0.

**Comment by popilas** [comment]
> > It's few lines of code.
> 
> Have you even seen the source code for version 1.4? It took me nearly a month to add multilang support while working on version 2.0.

2 version is good but only need
x04[CS:GO]^x01 Wyswietlanie skinow zostalo^x03 %s^x01.", playerData[id][SKINS_DISABLED] ? "wylaczone" : "wlaczone");
I will test tomorrow 2.5.3
