### ISSUE TITLE
containing one of the default skins does not exist

### ISSUE THREAD

**Issue by lawrbeast** [TheDoctor0/CSGOMod#109]
L 01/05/2021 - 02:47:25: [CS:GO] The file models/csgo_v2_skins/hegrenade/v_hegrenade_0.mdl containing one of the default skins does not exist!
L 01/05/2021 - 02:47:25: [CS:GO] The file models/csgo_v2_skins/c4/v_c4_0.mdl containing one of the default skins does not exist!
L 01/05/2021 - 02:47:25: [CS:GO] The file models/csgo_v2_skins/smokegrenade/v_smokegrenade_0.mdl containing one of the default skins does not exist!
L 01/05/2021 - 02:47:25: [CS:GO] The file models/csgo_v2_skins/flashbang/v_flashbang_0.mdl containing one of the default skins does not exist!
L 01/05/2021 - 02:47:25: [AMXX] Plugin ("csgo_core.amxx") is setting itself as failed.
L 01/05/2021 - 02:47:25: [AMXX] Plugin says: [CS:GO] Not all the skins were loaded. Check the error logs!
L 01/05/2021 - 02:47:25: [AMXX] Run time error 1 (plugin "csgo_core.amxx") - forced exit
Executing ReGameDLL Configuration File

There is no v_hegrenade_0.mdl and the others in the models folder

**Comment by TheDoctor0** [comment]
Fixed in https://github.com/TheDoctor0/CSGOMod/releases/tag/2.5.4.
