### ISSUE TITLE
change map in 1.4

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#11]
Is it normal to take too long to change the map? sometimes the server goes down and comes back in another

**Comment by ksm200** [comment]
> Is it normal to take too long to change the map? sometimes the server goes down and comes back in another

or was this fixed in 2.0?

**Comment by TheDoctor0** [comment]
> sometimes the server goes down and comes back in another
If that's the case the server is probably crashing because of famous 512 resources precache limit.
Version 2.0 is using submodels, so there are much less files in precache and that isn't an issue anymore.

**Comment by ksm200** [comment]
perfect
