### ISSUE TITLE
question about vip ammo and vip free time

### ISSUE THREAD

**Issue by popilas** [TheDoctor0/CSGOMod#110]
Hello im here again.. i hope these will be the last questions
1) How i can do for vip weapons like deagle and ak47 or m4a1 ammo pcs
A. VIP get deagle 7/7 ammo ak and m4 30/30     need do like svip.
B.SVIP get deagle 7/35 ammo ak and m4 30/90

2)Free VIP or SVIP start hour
Free vip or svip does not respond to exact hours and does not work accurately.

for example:
// Free VIP or SVIP type.
// 1 - SVIP
// 0 - VIP
//
// Default "0"
**csgo_vip_svip_free_type "0"**

// Default "19"
csgo_vip_svip_free_vip_from "12"

// Free VIP or SVIP end hour.
//
// Default "9"
csgo_vip_svip_free_vip_to "13"

vip works after 13 after map changes.

The server timezone is correct

And
// Set options for player aim hud message info.
// "a" - display health / armor/ weapon for teammates
// "b" - display rank for teammates
// "c" - display rank for enemies
// "d" - move the info below people heads
//
// Default "ab"
csgo_ranks_icon_flags "abcd"
Dont work when leave ad showing enemny name and rank

AND
// Minimum number of players on the server to earn the euro, change ELO rank and count operations.
//
// Default "4"
csgo_min_players "4"
ELO points works when 2 players are playing 
everything else works well

**Comment by TheDoctor0** [comment]
If you want to ask a question and report bugs please create a new issue every single time.

About your question, you can use [cs_set_user_bpammo](https://www.amxmodx.org/api/cstrike/cs_set_user_bpammo) after weapon assignment.
