### ISSUE TITLE
ELO change on kill

### ISSUE THREAD

**Issue by TheDoctor0** [TheDoctor0/CSGOMod#111]
`csgo_get_min_players` do not block ELO change on kill - it should as described in https://github.com/TheDoctor0/CSGOMod/issues/110.

**Comment by popilas** [comment]
Hello, I just tested new csgo_ranks from 2.5.4 and 2 players playing and they give elo points

**Comment by TheDoctor0** [comment]
This change is not included in 2.5.4.
