### ISSUE TITLE
Free VIP hours

### ISSUE THREAD

**Issue by TheDoctor0** [TheDoctor0/CSGOMod#112]
Free VIP is not working as expected when `csgo_vip_svip_free_vip_from` value is bigger than `csgo_vip_svip_free_to` - #110.

**Comment by popilas** [comment]
Just tested 2.5.6 csgo_vip_svip and for me dont work free vip hours exmp from : 14 to : 16

**Comment by TheDoctor0** [comment]
Version 2.5.6 just has been re-released, it should work fine now.
