### ISSUE TITLE
rank

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#12]
![20200725135357_1](https://user-images.githubusercontent.com/64114407/88461946-6beb3800-ce7e-11ea-8d3c-99120ed233e6.jpg)
its normal ? in top15 Unranked with 613.34 points

the 1,2 and 3 in top15 not stay with tag [TOP1], [TOP2] and [TOP3] correct

**Comment by TheDoctor0** [comment]
Unranked players are not being excluded from elo top15. I will probably change that.

About prefixes, those are for overall top15 not elo top15, as it does not change so frequently.
