### ISSUE TITLE
Issue with CS:GO Clans

### ISSUE THREAD

**Issue by Happy2906** [TheDoctor0/CSGOMod#120]
I was checking out your latest release and it's awesome! 

I have no idea what is exactly going on, but CS:GO clans cannot connect with my data base. I tried to reinstall everything, but nothing changed. Everything else works fine, except this. 

[CS:GO Clans] Init SQL Error: Can't connect to MySQL server on 'sql.pukawka.pl' (4) (2003)

**Comment by TheDoctor0** [comment]
Hello.
Sorry for such a delayed response, but right now I don't have time for active support of this mod.

You can try debugging this issue by logging database credentials to check if they are correct.
Add `log_amx("Host: %s | User: %s | Pass: %s | DB: %s", host, user, pass, db);` in line 2476 and recompile this plugin.

**Comment by Happy2906** [comment]
Hi Dawid,

Yes all the details for database are correct because everything runs as it should be running. This is just one plugin that does not want to connect to the database.
 In my database, all rows and columns are created automatically after you connect to the database. Everything is there except clans.

**Comment by Happy2906** [comment]
I have connected to a different database and it's all working fine. I'm so sorry for the trouble. Hope you have a good one!
