### ISSUE TITLE
Native Error

### ISSUE THREAD

**Issue by Happy2906** [TheDoctor0/CSGOMod#122]
Hi,

I was testing the latest release with my friends and two plugins have stopped working and this error popped up in the game console-

L 03/27/2021 - 21:17:11: [AMXX] Displaying debug trace (plugin "csgo_ranks.amxx", version "2.5.7")
L 03/27/2021 - 21:17:11: [AMXX] Run time error 10: native error (native "csgo_get_user_operation_text")
L 03/27/2021 - 21:17:11: [AMXX]    [0] csgo_ranks.sma::display_hud (line 613)
L 03/27/2021 - 21:17:11: Invalid index 8 (count: 5)
L 03/27/2021 - 21:17:11: [AMXX] Displaying debug trace (plugin "csgo_operations.amxx", version "2.5.7")
L 03/27/2021 - 21:17:11: [AMXX] Run time error 10: native error (native "ArrayGetArray")
L 03/27/2021 - 21:17:11: [AMXX]    [0] csgo_operations.sma::get_operation_info (line 373)
L 03/27/2021 - 21:17:11: [AMXX]    [1] csgo_operations.sma::get_progress_need (line 394)
L 03/27/2021 - 21:17:11: [AMXX]    [2] csgo_operations.sma::get_progress (line 391)
L 03/27/2021 - 21:17:11: [AMXX]    [3] csgo_operations.sma::_csgo_get_user_operation_text (line 403)
L 03/27/2021 - 21:17:11: Unhandled dynamic native error

Any idea how to fix this?

**Comment by TheDoctor0** [comment]
Hello.
Did you make any changes to the configuration of operations?

**Comment by Happy2906** [comment]
Nothing has been touched. All the files that are in the release were just installed on the server. It's quite weird because when I'm on the server by myself it works fine, but as soon as someone joins me, this error shows up.

**Comment by Happy2906** [comment]
It has been sorted out. Sorry for trouble.
