### ISSUE TITLE
Issue on c4 and defuse kit

### ISSUE THREAD

**Issue by NiceFeatures** [TheDoctor0/CSGOMod#137]
If you uncomment the #define DISABLE_SUBMODELS, when changing the weapon to one that has a skin, the defuse kit disappears from the CT and the c4 disappears from the back of the TR.

**Comment by TheDoctor0** [comment]
I'll verify it and if that's really the case it should be a pretty straightforward issue to fix.

**Comment by Zetz512** [comment]
Hello!! i have the same problem but #define DISABLE_SUBMODELS is commented...

When you spawn in start round, who terrorist spawn with c4, it doesn't appear in the back, happen too with defuse kit on CT's
But if i drop C4 and pick up again, its show up... and now when i plant the bomb i still have the c4 model in my back

image: https://prnt.sc/1uad58m

u can see someone's killed me after i plant the bomb and u see i still have the c4 in my back

ty!

**Comment by TheDoctor0** [comment]
Hi @Zetz512, I actually did not make a release containing this fix yet.
You can get the [csgo_mod.sma](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_core.sma) and try if it works for you.

**Comment by Zetz512** [comment]
now works fine! ty!
