### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#14]
![20200725150548_1](https://user-images.githubusercontent.com/64114407/88463347-727ead00-ce88-11ea-92da-d8338013c632.jpg)

suggestion to see the model before buying

**Comment by TheDoctor0** [comment]
It has been added in [Beta 5](https://github.com/TheDoctor0/CSGOMod/releases/tag/2.0-beta5) 5 days ago.
