### ISSUE TITLE
Market Skin Bug

### ISSUE THREAD

**Issue by NiceFeatures** [TheDoctor0/CSGOMod#144]
The skin market has a bug:
If the owner of the skin for sale is offline, the buyer pays the price of the skin and receives it, but the seller does not receive this money.

**Comment by TheDoctor0** [comment]
I just checked and that should not be possible.
After the player disconnects his skins [are removed from the market](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_core.sma#L485).

Can you provide more details?
