### ISSUE TITLE
Inspect skin

### ISSUE THREAD

**Issue by drag1c** [TheDoctor0/CSGOMod#147]
Whenever pressed F (inspect), no matter of which skin on pistols, it shows models even if default one is present (for example new players).
For example, on glock for me is showing assimov.

I've tried with steam and gsclient user - it is the same.

**Comment by drag1c** [comment]
It happens and with weapons, even if some skin is attached (it shows different one until shots fired).

**Comment by drag1c** [comment]
Small update:
It does not happens in previous version of plugin.
I assume, problem is here:
[https://github.com/TheDoctor0/CSGOMod/commit/053497af2d795e91988a934e085638f0a5d4c6a3#diff-d49e330cf1ade533bb3bb0b068ba97aa0fcf9171d60641724a29dfb960427c29](url)

**Comment by TheDoctor0** [comment]
> It does not happens in previous version of plugin.
> I assume problem happened after update for Fix disappearing c4/defuse kit.

This is valuable information. I'll check it out!

**Comment by Ziome3eg** [comment]
i've found fix:
in csgo_core.sma change: 
inside public deploy_weapon_switch(id)
add `set_pev(id, pev_body, skin[SKIN_SUBMODEL]);` under both `set_pev(id, pev_viewmodel2, skin[SKIN_MODEL]);`

**Comment by Ziome3eg** [comment]
i've found additional bug that if someone inspect default weapon it'll get last submodel in memory, but fixed it with this:
in csgo_core.sma change:
inside public deploy_weapon_switch(id)
add `set_pev(id, pev_body, 0);` under both `set_pev(id, pev_viewmodel2, defaultSkin);`
