### ISSUE TITLE
crashes at csgo_default_skins "0"

### ISSUE THREAD

**Issue by drag1c** [TheDoctor0/CSGOMod#148]
If csgo_default_skins "0" and player buys mp5, server crashes.

Probably because weapon name in plugin is mp5navy.

**Comment by Czarintax** [comment]
Yeah,
Fixed that issue with:
[csgo_core.sma#L3096](https://github.com/Czarintax/CSGOMod/blob/d4d78964f498d9c6c2abc922c23f458e538ed470/cstrike/addons/amxmodx/scripting/csgo_core.sma#L3096)
