### ISSUE TITLE
error and server crash

### ISSUE THREAD

**Issue by Damigeana** [TheDoctor0/CSGOMod#15]
L 07/28/2020 - 22:32:06: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 07/28/2020 - 22:32:06: [FAKEMETA] Invalid entity
L 07/28/2020 - 22:32:06: [AMXX] Run time error 10 (plugin "csgo_mod.amxx") (native "pev") - debug not enabled!
L 07/28/2020 - 22:32:06: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 07/28/2020 - 22:32:06: [FAKEMETA] Invalid entity
L 07/28/2020 - 22:32:06: [AMXX] Run time error 10 (plugin "csgo_mod.amxx") (native "pev") - debug not enabled!
L 07/28/2020 - 22:32:06: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 07/28/2020 - 22:32:06: [FAKEMETA] Invalid entity
L 07/28/2020 - 22:32:06: [AMXX] Run time error 10 (plugin "csgo_mod.amxx") (native "pev") - debug not enabled!
L 07/28/2020 - 22:32:06: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).

**Comment by NoahLTU** [comment]
Use debug

**Comment by Damigeana** [comment]
> Use debug

L 07/29/2020 - 16:47:49: [FAKEMETA] Invalid entity
L 07/29/2020 - 16:47:49: [AMXX] Displaying debug trace (plugin "csgo_mod.amxx", version "2.0")
L 07/29/2020 - 16:47:49: [AMXX] Run time error 10: native error (native "pev")
L 07/29/2020 - 16:47:49: [AMXX] [0] csgo_mod.sma::update_client_data_post (line 2218)
