### ISSUE TITLE
Unpreacacher

### ISSUE THREAD

**Issue by Happy2906** [TheDoctor0/CSGOMod#153]
Hi,

Just a quick question, can you use the unprecacher module on the older versions? I am currently running on version 1.4. Some of the maps such as css_dust2_go, they don't work, because I get an error with 512 limit and I'm trying to find a solution to resolve this problem. If I can use, could you please advise me on how to configure the module please? 

Merry Christmas!

**Comment by TheDoctor0** [comment]
Hello @Happy2906.
Of course that you can use the Unprecacher module with older versions of the mod.
You will probably only need to change [the config](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/unprecacher/list.ini) a little.

From what I remember it was only hard to with the 512 limit on cobblestone and overpass.
Both of those maps use quite a lot of models by themselves, so it greatly reduces the number of skins that can be used.

**Comment by Happy2906** [comment]
As far as I can see, the version 1.4 only contains v_ models. Once I disable the submodels, the original models from 1.6 disappear and I need both of them, as some players play without the CS:GO models. 

Is there any other way that I can use this modules, to reduces resources on the server?
