### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by Haise420** [TheDoctor0/CSGOMod#158]
ReGameDLL version: 5.21.0.556-dev
L 10/26/2022 - 02:33:05: -------- Mapchange to csgo_aztec --------
L 10/26/2022 - 02:33:07: [csgo_core.amxx] CS:GO Mod by O'Zone (v2.5.11).
L 10/26/2022 - 02:33:07: [csgo_core.amxx] Loaded 1231 skins from 71 files.
Executing ReGameDLL Configuration File 
exec /addons/metamod/revoice_plus/revoice.cfg: invalid path.
[AMXX] Loaded 2 admins from file
Executing AMX Mod X Configuration File 
Scrolling message displaying frequency: 10:00 minutes
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
dlopen failed trying to load:
/home/servers/soldiergang_cs16/.steam/sdk32/libsteam.so
with error:
/home/servers/soldiergang_cs16/.steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory
**FATAL ERROR (shutting down): Cache_TryAlloc: 15103488 is greater then free hunk**
Segmentation fault
./hlds_run: 201: gdb: not found
email debug.log to linux@valvesoftware.com
Wed 26 Oct 2022 02:33:07 AM CEST: Server restart in 10 seconds

I rent this server from some hosting and im not allowed to change start server options, so what do I do?

**Comment by TheDoctor0** [comment]
Hi @Haise420.
This is a known issue listed in [README](https://github.com/TheDoctor0/CSGOMod#known-issues).
The majority of the server hostings allow adding custom starting options where you need to put `-heapsize 65536`.
