### ISSUE TITLE
weapon_p228

### ISSUE THREAD

**Issue by Damigeana** [TheDoctor0/CSGOMod#16]
[CS:GO StatTrak] Query failed. [1364] Field 'weapon_p228' doesn't have a default value

**Comment by TheDoctor0** [comment]
You already reported it here: https://github.com/TheDoctor0/CSGOMod/issues/9
It has been already fixed in [this commit](https://github.com/TheDoctor0/CSGOMod/commit/5f8b80f6b57d83132cdc6d6e6bc14f308c407702), but it's such a minor change that I will wait with it for final 2.0 release.
