### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Damigeana** [TheDoctor0/CSGOMod#17]
L 07/31/2020 - 15:48:28: [AMXX] Displaying debug trace (plugin "csgo_mod.amxx", version "2.0")
L 07/31/2020 - 15:48:28: [AMXX] Run time error 10: native error (native "pev")
L 07/31/2020 - 15:48:28: [AMXX] [0] fakemeta_util.inc::fm_get_aim_origin (line 737)
L 07/31/2020 - 15:48:28: [AMXX] [1] csgo_mod.sma::fm_get_user_aiming_ent (line 3176)
L 07/31/2020 - 15:48:28: [AMXX] [2] csgo_mod.sma::check_aim_weapon (line 2313)
L 07/31/2020 - 15:48:29: [FAKEMETA] Invalid entity

**Comment by TheDoctor0** [comment]
Both player id and entity id are properly validated in check_aim_weapon function.
In what situation this error occurred? I need a detailed description, so I can replicate this issue.

**Comment by Damigeana** [comment]
You can enter on me server and test.
I was played with me friend he was ct i was terro.

**Comment by TheDoctor0** [comment]
That's not really a detailed description of the problem.
You need to write exactly what you and your friend are doing when server crashed,
so we can narrow the cause of the problem and then fix it - if it's not the issue with the server itself..

**Comment by Damigeana** [comment]
Basicaly i was just playing on the map. After some time like 4-5 min server crash. So i didnt do something special.
I dont know how to describe. Was just moving around the map.

**Comment by TheDoctor0** [comment]
Can you add _-debug_ to server starting parameters and then provide a crash report (_debug.log_ in root directory)?

**Comment by Damigeana** [comment]
I cant i was buying the server i didnt hosted.

**Comment by Damigeana** [comment]
CRASH: Tue Jul 28 21:01:48 UTC 2020
Start Line: ./hlds_linux -console -game cstrike -port 27015 -sport 26900 +map de_dust2 +ip 188.212.101.196 -pingboost 2 -secure -debug +fps_max 0 +sys_ticrate 1000 -zone 8192 +maxplayers 32 -heapsize 1048576 -pidfile hlds.39.pid
End of crash report
----------------------------------------------
----------------------------------------------
CRASH: Tue Jul 28 21:33:36 UTC 2020
Start Line: ./hlds_linux -console -game cstrike -port 27015 -sport 26900 +map de_dust2 +ip 188.212.101.196 -pingboost 2 -secure -debug +fps_max 0 +sys_ticrate 1000 -zone 8192 +maxplayers 32 -heapsize 1048576 -pidfile hlds.39.pid
End of crash report
----------------------------------------------
----------------------------------------------
CRASH: Tue Jul 28 22:32:13 UTC 2020
Start Line: ./hlds_linux -console -game cstrike -port 27015 -sport 26900 +map de_dust2 +ip 188.212.101.196 -pingboost 2 -secure -debug +fps_max 0 +sys_ticrate 1000 -zone 8192 +maxplayers 32 -heapsize 1048576 -pidfile hlds.39.pid
End of crash report
----------------------------------------------
----------------------------------------------
CRASH: Tue Jul 28 22:39:32 UTC 2020
Start Line: ./hlds_linux -console -game cstrike -port 27015 -sport 26900 +map de_dust2 +ip 188.212.101.196 -pingboost 2 -secure -debug +fps_max 0 +sys_ticrate 1000 -zone 8192 +maxplayers 32 -heapsize 1048576 -pidfile hlds.39.pid
End of crash report
----------------------------------------------
----------------------------------------------
CRASH: Tue Jul 28 22:49:05 UTC 2020
Start Line: ./hlds_linux -console -game cstrike -port 27015 -sport 26900 +map de_dust2 +ip 188.212.101.196 -pingboost 2 -secure -debug +fps_max 0 +sys_ticrate 1000 -zone 8192 +maxplayers 32 -heapsize 1048576 -pidfile hlds.39.pid
End of crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Jul 29 03:40:40 UTC 2020
Start Line: ./hlds_linux -console -game cstrike -port 27015 -sport 26900 +map de_dust2 +ip 188.212.101.196 -pingboost 2 -secure -debug +fps_max 0 +sys_ticrate 1000 -zone 8192 +maxplayers 32 -heapsize 1048576 -pidfile hlds.39.pid
End of crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Jul 29 16:47:50 UTC 2020
Start Line: ./hlds_linux -console -game cstrike -port 27015 -sport 26900 +map de_dust2 +ip 188.212.101.196 -pingboost 2 -secure -debug +fps_max 0 +sys_ticrate 1000 -zone 8192 +maxplayers 32 -heapsize 1048576 -pidfile hlds.40.pid
End of crash report
----------------------------------------------
----------------------------------------------
CRASH: Fri Jul 31 15:48:32 UTC 2020
Start Line: ./hlds_linux -console -game cstrike -port 27015 -sport 26900 +map de_dust2 +ip 188.212.101.196 -pingboost 2 -secure -debug +fps_max 0 +sys_ticrate 1000 -zone 8192 +maxplayers 32 -heapsize 1048576 -pidfile hlds.38.pid
End of crash report
----------------------------------------------

**Comment by Damigeana** [comment]
L 28/07/2020 - 22:32:13: (map "csgo_dust2") PF_MessageBegin_I: with no target entity

L 31/07/2020 - 15:48:32: (map "csgo_dust3") PF_MessageBegin_I: with no target entity

**Comment by TheDoctor0** [comment]
Does this issue still occur? on your server

**Comment by Damigeana** [comment]
Yes is still crashing. I dont know Why.

**Comment by Damigeana** [comment]
i get the same error
L 08/18/2020 - 12:47:00: [FAKEMETA] Invalid entity
L 08/18/2020 - 12:47:00: [AMXX] Displaying debug trace (plugin
"csgo_mod.amxx", version "2.0.0")
L 08/18/2020 - 12:47:00: [AMXX] Run time error 10: native error (native
"pev")
L 08/18/2020 - 12:47:00: [AMXX]    [0] fakemeta_util.inc::fm_get_aim_origin
(line 737)
L 08/18/2020 - 12:47:00: [AMXX]    [1] csgo_mod.sma::fm_get_user_aiming_ent
(line 3187)
L 08/18/2020 - 12:47:00: [AMXX]    [2] csgo_mod.sma::check_aim_weapon (line
2324)

În mar., 18 aug. 2020 la 23:14, The Gaming Cousin <cimpeanuflavius@gmail.com>
a scris:

**Comment by Damigeana** [comment]
I think i find some of them. i`m not sure
L 16/08/2020 - 19:28:25: (map "csgo_dust") PF_MessageBegin_I: with no
target entity

L 16/08/2020 - 19:58:44: (map "csgo_dust2") PF_MessageBegin_I: with no
target entity

L 17/08/2020 - 06:50:06: (map "csgo_port") Mod_LoadTextures: Texture
)—]~Än<Îb‘Ô‰Ê¯r¹x Ä TØa”ðz¡Û”Ò›”Çæ_–GvØ° â ¼”ªènÒöS¾÷vöÆ¡¼~qâx¼ìx
ë`¢sgÄÔ•œVIÁ0@œRžž ZÈ4‘ð ¾\)šC'v=:–Agä/€¶~ÈÁ_åk‘ã'—ôVœˆZ£ÐtÂÂ-
gh´e<¼nvÈmÞ§Kšm‘Ø‚e÷† ðKÒð®Ò–jŽâe–y_Ì– åU Ê ëÜv…ë–©—vöð ÂejØj
ðj„ë;²X4ÆâŽ¶ž4Á2MÃl¦ž y¬=£Õ `s2ˆC z-4~:PÈHÈ}zÓ¶ ád‘æ= èdœ=M ÕlrÃ)œ]r»f<Äb„»
Ä´nš† Äm<÷qfùK$W is not 16 aligned
L 17/08/2020 - 14:18:47: (map "csgo_port") Mod_LoadTextures: Texture
)—]~Än<Îb‘Ô‰Ê¯r¹x Ä TØa”ðz¡Û”Ò›”Çæ_–GvØ° â ¼”ªènÒöS¾÷vöÆ¡¼~qâx¼ìx
ë`¢sgÄÔ•œVIÁ0@œRžž ZÈ4‘ð ¾\)šC'v=:–Agä/€¶~ÈÁ_åk‘ã'—ôVœˆZ£ÐtÂÂ-
gh´e<¼nvÈmÞ§Kšm‘Ø‚e÷† ðKÒð®Ò–jŽâe–y_Ì– åU Ê ëÜv…ë–©—vöð ÂejØj
ðj„ë;²X4ÆâŽ¶ž4Á2MÃl¦ž y¬=£Õ `s2ˆC z-4~:PÈHÈ}zÓ¶ ád‘æ= èdœ=M ÕlrÃ)œ]r»f<Äb„»
Ä´nš† Äm<÷qfùK$W is not 16 aligned
L 18/08/2020 - 05:45:15: (map "csgo_port") Mod_LoadTextures: Texture
)—]~Än<Îb‘Ô‰Ê¯r¹x Ä TØa”ðz¡Û”Ò›”Çæ_–GvØ° â ¼”ªènÒöS¾÷vöÆ¡¼~qâx¼ìx
ë`¢sgÄÔ•œVIÁ0@œRžž ZÈ4‘ð ¾\)šC'v=:–Agä/€¶~ÈÁ_åk‘ã'—ôVœˆZ£ÐtÂÂ-
gh´e<¼nvÈmÞ§Kšm‘Ø‚e÷† ðKÒð®Ò–jŽâe–y_Ì– åU Ê ëÜv…ë–©—vöð ÂejØj
ðj„ë;²X4ÆâŽ¶ž4Á2MÃl¦ž y¬=£Õ `s2ˆC z-4~:PÈHÈ}zÓ¶ ád‘æ= èdœ=M ÕlrÃ)œ]r»f<Äb„»
Ä´nš† Äm<÷qfùK$W is not 16 aligned
L 18/08/2020 - 12:47:06: (map "csgo_nuke_old") PF_MessageBegin_I: with no
target entity

L 18/08/2020 - 20:31:06: (map "csgo_port") Mod_LoadTextures: Texture
)—]~Än<Îb‘Ô‰Ê¯r¹x Ä TØa”ðz¡Û”Ò›”Çæ_–GvØ° â ¼”ªènÒöS¾÷vöÆ¡¼~qâx¼ìx
ë`¢sgÄÔ•œVIÁ0@œRžž ZÈ4‘ð ¾\)šC'v=:–Agä/€¶~ÈÁ_åk‘ã'—ôVœˆZ£ÐtÂÂ-
gh´e<¼nvÈmÞ§Kšm‘Ø‚e÷† ðKÒð®Ò–jŽâe–y_Ì– åU Ê ëÜv…ë–©—vöð ÂejØj
ðj„ë;²X4ÆâŽ¶ž4Á2MÃl¦ž y¬=£Õ `s2ˆC z-4~:PÈHÈ}zÓ¶ ád‘æ= èdœ=M ÕlrÃ)œ]r»f<Äb„»
Ä´nš† Äm<÷qfùK$W is not 16 aligned


În mie., 19 aug. 2020 la 01:21, The Gaming Cousin <cimpeanuflavius@gmail.com>
a scris:

**Comment by TheDoctor0** [comment]
There are already few quite popular servers that use 2.0 version and do not seems to have similar issues.

> L 08/18/2020 - 12:47:00: [AMXX]    [2] csgo_mod.sma::check_aim_weapon (line 2324)
That is especially weird, because would suggest that player that is not connected is aiming at something.
Which of course is not possible and before using fm_get_user_aiming_ent there is a check if player is alive.

> L 16/08/2020 - 19:58:44: (map "csgo_dust2") PF_MessageBegin_I: with no target entity
There is no usage of message_begin with MSG_ONE or MSG_ONE_UNRELIABLE without target in any plugin.
Do you have any plugins beside standard for AMXX and from this mod?

> L 18/08/2020 - 20:31:06: (map "csgo_port") Mod_LoadTextures: Texture (...) is not 16 aligned
This is the first time in my life that I see this error.
There is [single Google result](http://www.dedicated-server.ru/vbb/showthread.php?t=23493) that is connected with CS 1.6/AMXX and the solution here was to reinstall server from scratch.
That seems resonable, because errors on your server do not seem to occur on other servers.
I would reinstall it, install [BasePack](https://github.com/AMXX-pl/BasePack) and the mod itself and then check if there is any change.

**Comment by Damigeana** [comment]
I dont have i was make a clean install on the server.


În mie., 19 aug. 2020 la 09:35, Dawid Janik <notifications@github.com> a
scris:

**Comment by TheDoctor0** [comment]
Show me the output for commands:
1. `version`
2. `meta version`
3. `meta list`
4. `amxx version`
5. `amxx plugins`

**Comment by Damigeana** [comment]
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.7.0.693-dev
Build date: 18:20:58 Jan 28 2020 (2117)
Build from: https://github.com/dreamstalker/rehlds/commit/c4cecf5

meta version
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:54 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70

meta list
Currently loaded plugins:
description stat pend file vers src load unload
[ 1] Reunion RUN - reunion_mm_i386.so v0.1.0.92 ini Start Never
[ 2] ReAuthCheck RUN - reauthcheck_mm_i386.so v0.1.6 ini Start Never
[ 3] AMX Mod X RUN - amxmodx_mm_i386.so v1.10.0.5406 ini Start ANY
[ 4] Ultimate Unprecacher RUN - unprecacher_mm_i386.so vBeta 2.5.3 ini
Chlvl Chlvl
[ 5] Fun RUN - fun_amxx_i386.so v1.10.0.5406 pl3 ANY ANY
[ 6] Engine RUN - engine_amxx_i386.so v1.10.0.5406 pl3 ANY ANY
[ 7] FakeMeta RUN - fakemeta_amxx_i386.so v1.10.0.5406 pl3 ANY ANY
[ 8] GeoIP RUN - geoip_amxx_i386.so v1.10.0.5406 pl3 ANY ANY
[ 9] CStrike RUN - cstrike_amxx_i386.so v1.10.0.5406 pl3 ANY ANY
[10] CSX RUN - csx_amxx_i386.so v1.10.0.5406 pl3 ANY ANY
[11] Ham Sandwich RUN - hamsandwich_amxx_i386.so v1.10.0.5406 pl3 ANY ANY
[12] hackdetector RUN - hackdetector_amxx_i386.so v0.15.328.lite pl3 ANY ANY
[13] MySQL RUN - mysql_amxx_i386.so v1.10.0.5406 pl3 ANY ANY
13 plugins, 13 running

AMX Mod X 1.10.0.5406 (http://www.amxmodx.org)
Authors:
David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Jul 31 2020 14:34:47
Built from: https://github.com/alliedmodders/amxmodx/commit/1027df0
Build ID: 5406:1027df0
Core mode: JIT+ASM32

[ 1] 0 NeoSecurity 0.1 [B] zorken unknown NeoSecurity running
[ 2] 1 Admin Base 1.10.0.540 AMXX Dev Team admin.amxx running
[ 3] 2 Admin Commands 1.10.0.540 AMXX Dev Team admincmd.am running
[ 4] 3 Admin Help 1.10.0.540 AMXX Dev Team adminhelp.a running
[ 5] 4 Slots Reservation 1.10.0.540 AMXX Dev Team adminslots. running
[ 6] 5 Multi-Lingual System 1.10.0.540 AMXX Dev Team multilingua running
[ 7] 6 Menus Front-End 1.10.0.540 AMXX Dev Team menufront.a running
[ 8] 7 Commands Menu 1.10.0.540 AMXX Dev Team cmdmenu.amx running
[ 9] 8 Players Menu 1.10.0.540 AMXX Dev Team plmenu.amxx running
[ 10] 9 Maps Menu 1.10.0.540 AMXX Dev Team mapsmenu.am running
[ 11] 10 Plugin Menu 1.10.0.540 AMXX Dev Team pluginmenu. running
[ 12] 11 OciXCrom's Admin Chat 3.1 OciXCrom unknown adminchat.a running
[ 13] 12 Anti Flood 1.10.0.540 AMXX Dev Team antiflood.a stopped
[ 14] 13 Scrolling Message 1.10.0.540 AMXX Dev Team scrollmsg.a running
[ 15] 14 Info. Messages 1.10.0.540 AMXX Dev Team imessage.am running
[ 16] 15 Admin Votes 1.10.0.540 AMXX Dev Team adminvote.a running
[ 17] 16 NextMap 1.10.0.540 AMXX Dev Team nextmap.amx running
[ 18] 17 Nextmap Chooser 1.10.0.540 AMXX Dev Team mapchooser. running
[ 19] 18 TimeLeft 1.10.0.540 AMXX Dev Team timeleft.am running
[ 20] 19 Pause Plugins 1.10.0.540 AMXX Dev Team pausecfg.am running
[ 21] 20 Stats Configuration 1.10.0.540 AMXX Dev Team statscfg.am running
[ 22] 21 StatsX 1.10.0.540 AMXX Dev Team statsx.amxx running
[ 23] 22 Admin Groups 1.2 OciXCrom unknown crx_admingr running
[ 24] 23 Chat Manager 4.5.1 OciXCrom unknown crx_chatman running
[ 25] 24 CM: Toggle Chat 4.1 OciXCrom unknown crx_chatman running
[ 26] 25 WarmUp Round 1.0 eXtreamCS unknown WarmUp.amxx running
[ 27] 26 Team Join Management 0.3 Exolent unknown team_join.a running
[ 28] 27 No Name Change 1.1 OciXCrom unknown crx_nonamec running
[ 29] 28 Ultimate Jump Anti Che 1.4.2 DediHost & Nikol unknown ultimate_ju
running
[ 30] 29 Show CS Version 0.1 Nikolow unknown amx_version running
[ 31] 30 Word Blocker 0.1 hornet unknown badwords.am running
[ 32] 31 HackDetector 0.15.lite Lev @ AGHL.RU De unknown hackdetecto running
[ 33] 32 Max Number in Name&Cha 1.0 OciXCrom unknown NameNumbers running
[ 34] 33 No retry 1.16 Priski unknown noretry.amx running
[ 35] 34 CS:GO Mod 2.0.0 O'Zone unknown csgo_mod.am debug
[ 36] 35 CS:GO Clans 2.0.0 O'Zone unknown csgo_clans. running
[ 37] 36 CS:GO Accounts 2.0.0 O'Zone unknown csgo_accoun running
[ 38] 37 CS:GO C4 2.0.0 O'Zone unknown csgo_c4.amx running
[ 39] 38 CS:GO Nades 2.0.0 O'Zone unknown csgo_nades. running
[ 40] 39 CS:GO VIP and SVIP 2.0.0 O'Zone unknown csgo_vip_sv running
[ 41] 40 CS:GO Server Menu 2.0.0 O'Zone unknown csgo_server running
[ 42] 41 CS:GO Transfer 2.0.0 O'Zone unknown csgo_transf running
[ 43] 42 CS:GO Operations 2.0.0 O'Zone unknown csgo_operat running
[ 44] 43 CS:GO Molotov 2.0.0 DynamicBits & O' unknown csgo_moloto running
[ 45] 44 CS:GO Smoke 2.0.0 Numb & O'Zone unknown csgo_smoke. running
[ 46] 45 CS:GO Zeus 2.0.0 wopox1337 & O'Zo unknown csgo_zeus.a running
[ 47] 46 CS:GO Run Boost 2.0.0 O'Zone unknown csgo_runboo running
[ 48] 47 CS:GO Inspect 2.0.0 O'Zone unknown csgo_inspec running
[ 49] 48 CS:GO Buy Menu 2.0.0 O'Zone unknown csgo_buymen running
[ 50] 49 CS:GO Rank System 2.0.0 O'Zone unknown csgo_ranks. running
[ 51] 50 CS:GO Assist and Reven 2.0.0 O'Zone unknown csgo_assist running
[ 52] 51 CS:GO StatTrak 2.0.0 O'Zone unknown csgo_stattr running
[ 53] 52 CS:GO No Distractions 2.0.0 O'Zone unknown csgo_no_dis running

În mie., 19 aug. 2020 la 14:39, Dawid Janik <notifications@github.com> a
scris:

**Comment by Damigeana** [comment]
I was getting error before to add them

**Comment by Damigeana** [comment]
Thats Why i sayid no

**Comment by TheDoctor0** [comment]
I've some changes in last day, so you can download latest version of plugins and csgomod.inc library, 
compile them and check if those errors still occur.

You may also try to reupload csgo_port map to solve this error with textures.
It's possible that map file was corrupted.

**Comment by Damigeana** [comment]
I’m gona wait till saturday when you realese the version.

**Comment by Damigeana** [comment]
I was compile them. I’m currently using the last  versione.
I dont know why is giving this errors.

**Comment by TheDoctor0** [comment]
Yeah, that's really a mystery.
There are 3 problems that you have and I cannot replicate any of them with nearly identical server setup.

**Comment by TheDoctor0** [comment]
> Run time error 10 (plugin "csa_bugfix.amxx") (native "pev") - debug not enabled!

It seems that you have similar problems with other plugins.

> FATAL ERROR (shutting down): PF_MessageBegin_I: with no target entity

As I said earlier, there is not a plugin in this mod that sends messages on MSG_ONE / MSG_UNRELIABLE channel without a target.

**Comment by Damigeana** [comment]
Is from csgo_mod plugin.

**Comment by TheDoctor0** [comment]
I added an [additional check](https://github.com/TheDoctor0/CSGOMod/commit/c2998a5acda746e49bc2b054ce3af6e2c7c76423) before creating sprite with rank icon. This is the last idea for this crash reason as there is not other place where message even has a target.

**Comment by Damigeana** [comment]
I think the problem is with the guns.

**Comment by TheDoctor0** [comment]
This is nothing helpful in determining the cause.. If I cannot replicate what's causing a crash, it's nearly impossible to fix it.
This issue is open for nearly a month and there is still not enough information.

@ksm200 [reported](https://github.com/TheDoctor0/CSGOMod/issues/32) a crash yesterday and even provided me with a demo.
I could debug it quite easily, because every single time I could check if server crashes when player dies from height damage.
I was crossing out possible reason after possible reason and it took me an hour to find and fix it.

**Comment by TheDoctor0** [comment]
Superseded by #35.
