### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by Damigeana** [TheDoctor0/CSGOMod#23]
Host_Error: ED_ParseEdict: Model '*258' failed to precache because the item count is over the 512 limit.
Reduce the number of brush models and/or regular models in the map to correct this.
FATAL ERROR (shutting down): Host_Error: ED_ParseEdict: Model '*258' failed to precache because the item count is over the 512 limit.
Reduce the number of brush models and/or regular models in the map to correct this.

**Comment by TheDoctor0** [comment]
Well, you an an answer here:
> Reduce the number of brush models and/or regular models in the map to correct this.
