### ISSUE TITLE
Error compile csgo_clans

### ISSUE THREAD

**Issue by Damigeana** [TheDoctor0/CSGOMod#24]
//// csgo_clans.sma
//
// C:\Users\cimpe\Desktop\csf\csgo_clans.sma(555) : error 017: undefined symbol "menuData"
// C:\Users\cimpe\Desktop\csf\csgo_clans.sma(555) : error 072: "sizeof" operator is invalid on "function" symbols
// C:\Users\cimpe\Desktop\csf\csgo_clans.sma(555) : error 029: invalid expression, assumed zero
// C:\Users\cimpe\Desktop\csf\csgo_clans.sma(555) : fatal error 107: too many error messages on one line
//
// Compilation aborted.

The rest of them working

**Comment by TheDoctor0** [comment]
I marked it as a WIP (work on progress).
