### ISSUE TITLE
Optionally allow to save accounts by SteamID

### ISSUE THREAD

**Issue by regener** [TheDoctor0/CSGOMod#29]
As the title says, add an option to allow the saving by SteamID instead of name.
- Good for the ones who change their name frequently
- The name check against the mysql escape characters can be skipped this way

-moved to https://github.com/TheDoctor0/CSGOMod/issues/30 -

**Comment by TheDoctor0** [comment]
> As the title says, add an option to allow the saving by SteamID instead of name.
That's a good suggestion, really useful for Steam only servers.

Can you make second issue about separation of M4A4 and M4A4?
It's much easier for me to track progress of individual ideas.

**Comment by ksm200** [comment]
I can give you another suggestion I have 1 zp plugin that saves by login and password and does not let the player connect to the server until registering or logging in to the account because in Brazil there are many problems with nick
if you want to add it on steam i will help you: eduardoscosta1995 (duh-)

**Comment by TheDoctor0** [comment]
> I can give you another suggestion I have 1 zp plugin that saves by login and password and does not let the player connect to the server until registering or logging in to the account because in Brazil there are many problems with nick
> if you want to add it on steam i will help you: eduardoscosta1995 (duh-)

The Polish language, similarly to Portuguese, also contains diacritical marks (such as: ą, ć, ę, ł, ń, ó, ś, ź, ż).
As long as your MySQL databases accepts UTF-8 characters (it should) there will be no issues with player names.
