### ISSUE TITLE
When i start the server i got some errors

### ISSUE THREAD

**Issue by Damigeana** [TheDoctor0/CSGOMod#3]
AMX Mod X version 1.9.0.5271 Copyright (c) 2004-2015 AMX Mod X Development Team
AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
This is free software and you are welcome to redistribute it under
certain conditions; type 'amxx gpl' for details.
L 07/16/2020 - 18:03:15: -------- Mapchange to de_dust2 --------
L 07/16/2020 - 18:03:17: [CS:GO] Plik models/csgo_ozone/elite/v_elite_5.mdl zawierajacy skin nie istnieje!
L 07/16/2020 - 18:03:17: [AMXX] Plugin ("csgo_mod.amxx") is setting itself as failed.
L 07/16/2020 - 18:03:17: [AMXX] Plugin says: [CS:GO] Nie zaladowano wszystkich skinow. Sprawdz logi bledow!
L 07/16/2020 - 18:03:17: [AMXX] Run time error 1 (plugin "csgo_mod.amxx") - forced exit
NeoSecurity.cfg cvars load
[AMXX] Loaded 0 admins from file
L 07/16/2020 - 18:03:17: Invalid CVAR pointer
L 07/16/2020 - 18:03:17: [AMXX] Run time error 10 (plugin "csgo_operations.amxx") (native "bind_pcvar_num") - debug not enabled!
L 07/16/2020 - 18:03:17: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 07/16/2020 - 18:03:17: Invalid CVAR pointer
L 07/16/2020 - 18:03:17: [AMXX] Run time error 10 (plugin "csgo_ranks.amxx") (native "bind_pcvar_num") - debug not enabled!
L 07/16/2020 - 18:03:17: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 07/16/2020 - 18:03:17: [CS:GO Clans] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 07/16/2020 - 18:03:17: [CS:GO Accounts] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 07/16/2020 - 18:03:17: Invalid array handle provided (0)
L 07/16/2020 - 18:03:17: [AMXX] Run time error 10 (plugin "csgo_operations.amxx") (native "ArrayPushArray") - debug not enabled!
L 07/16/2020 - 18:03:17: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 07/16/2020 - 18:03:17: [CS:GO Ranks] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 07/16/2020 - 18:03:17: [CS:GO StatTrak] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)

**Comment by Damigeana** [comment]
Is missing the v_elite_5.mdl that whan i fixit with another model just renamed.

but is not getting connected to mysql
L 07/16/2020 - 18:14:13: [CS:GO Mod] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 07/16/2020 - 18:14:13: [CS:GO Clans] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 07/16/2020 - 18:14:13: [CS:GO Accounts] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 07/16/2020 - 18:14:13: [CS:GO Ranks] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 07/16/2020 - 18:14:13: [CS:GO StatTrak] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)

**Comment by Damigeana** [comment]
Fix the mysql error. I change the amxmodx libraries from 1.9 back to 1.8.2 just the mysql one.

**Comment by TheDoctor0** [comment]
Thank you for pointing out that model in csgo_skins.ini. I'll fix that in a minute.

About problem with mysql, it's not related to this mod, it's internal problem with this module in some amxx 1.9.0 builds.
You can downgrade it to 1.8.2 as you did or alternatively use amxx 1.10.0 - for example from my [BasePack](https://github.com/AMXX-pl/BasePack).
