### ISSUE TITLE
Separate M4A4 from M4A1

### ISSUE THREAD

**Issue by regener** [TheDoctor0/CSGOMod#30]
*The other suggestion is to limit the usage of the silencer (M4A4 vs M4A1) by code with something like this:*

```
	if(Silencer[id] == false) // case M4A4
	{
		cs_set_weapon_silen(iEnt, 0); // remove the silencer
		set_pdata_float(iEnt , 47 , 9999.0, 4); // delay the secondary attack to prevent adding the silencer
	}
	else if(Silencer[id] == true) // case M4A1
	{
		cs_set_weapon_silen(iEnt, 1, 0); // adds the silencer (without animation)
	}
```

**Comment by TheDoctor0** [comment]
I think M4A1 animation for removing silencer is fine, but silencer should be attached by default as it is in CS:GO (same for USP).

About M4A4 skins, secondary attack should be blocked to prevent triggering non-existing animation that blocks shooting and using silencer at all.
