### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by DevilBoy-eXe** [TheDoctor0/CSGOMod#34]
I will leave here some suggestions that could be added to the mod

1: Nametag for weapons
2 : MVP
3: Music kits
4: Graffiti (https://gamebanana.com/wips/46110)
5: Mod selector by cvar competitive/casual/deathmach
6: Modification of the existing rank system by adding a function also to rank down not only up (idk if it's already like that)
7: Gambling like roulette, crash, coinflip, jackpot etc
8: Stattrak convertor, (convert a normal skin to stattrak in exchange of some money but with chance to fail)
9: Promocode (admin will set a promocode that will give some money if is known and used)
10: Skins categories (like in csgo https://counterstrike.fandom.com/wiki/Skins)
11: Skins classification (Factory New / Minimal Wear / Field-Tested / Well-Worn / Battle-Scared and lowering in level by how much is used for example Factory New have 100% if you use it all day it will decresse to 70% and will become Minimal Wear dealing less dmg and soo on)
12: Skin preview (being able to see the skin without owning it by equipping it for like 10 seconds)
13: Chat tag that can be purchased from store
14: Contract system like in csgo (ex: you put 10 common skins and you get 1 uncommon skin)
15: Daily Reward and Task

I would be great to be all added to the mod :)

**Comment by TheDoctor0** [comment]
I'll select suggestions based at what I said ealier and create an issue for each one so progress for them can be tracked separately.
