### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#35]
L 08/25/2020 - 14:52:53: [FAKEMETA] Invalid entity
L 08/25/2020 - 14:52:53: [AMXX] Displaying debug trace (plugin "csgo_core.amxx", version "2.1.0")
L 08/25/2020 - 14:52:53: [AMXX] Run time error 10: native error (native "pev")
L 08/25/2020 - 14:52:53: [AMXX]    [0] fakemeta_util.inc::fm_get_aim_origin (line 737)
L 08/25/2020 - 14:52:53: [AMXX]    [1] csgo_core.sma::fm_get_user_aiming_ent (line 3487)
L 08/25/2020 - 14:52:53: [AMXX]    [2] csgo_core.sma::check_aim_weapon (line 2542)

Server crashed with 3 players online

**Comment by TheDoctor0** [comment]
Does your server run with `-debug` in starting options?
Are there any logs in `debug.log` outside `cstrike` directory?

**Comment by ksm200** [comment]
L 24/08/2020 - 02:22:52: (map "csgo_dust2_new") Cache_TryAlloc: 11461024 is greater then free hunk
L 24/08/2020 - 08:24:50: (map "csgo_dust2_new") Cache_TryAlloc: 11461024 is greater then free hunk
L 24/08/2020 - 14:26:54: (map "csgo_dust2_new") Cache_TryAlloc: 11461024 is greater then free hunk
L 25/08/2020 - 03:39:05: (map "csgo_dust2_new") Cache_TryAlloc: 11461024 is greater then free hunk
L 25/08/2020 - 06:40:22: (map "csgo_cobblestone") Host_Error: ED_ParseEdict: Model '*258' failed to precache because the item count is over the 512 limit.
Reduce the number of brush models and/or regular models in the map to correct this.

L 25/08/2020 - 09:41:37: (map "csgo_cobblestone") Host_Error: ED_ParseEdict: Model '*258' failed to precache because the item count is over the 512 limit.
Reduce the number of brush models and/or regular models in the map to correct this.

L 25/08/2020 - 12:42:57: (map "csgo_cobblestone") Host_Error: ED_ParseEdict: Model '*258' failed to precache because the item count is over the 512 limit.
Reduce the number of brush models and/or regular models in the map to correct this.

L 25/08/2020 - 14:52:53: (map "csgo_dust2") PF_MessageBegin_I: with no target entity

**Comment by TheDoctor0** [comment]
> L 25/08/2020 - 03:39:05: (map "csgo_dust2_new") Cache_TryAlloc: 11461024 is greater then free hunk

You can fix this by adding `-heapsize 65536` to server starting options as described in [README](https://github.com/TheDoctor0/CSGOMod#known-issues). 
You can also try to increase heapsize value (for example to 131072) if server is still crashing on this map.

> L 25/08/2020 - 09:41:37: (map "csgo_cobblestone") Host_Error: ED_ParseEdict: Model '*258' failed to precache because the item count is over the 512 limit. Reduce the number of brush models and/or regular models in the map to correct this.

I assume you are using additional plugins with models/sprites, so this map probably won't work for you.

> L 25/08/2020 - 14:52:53: (map "csgo_dust2") PF_MessageBegin_I: with no target entity

Seems to be related to #17. I [implemented](https://github.com/TheDoctor0/CSGOMod/commit/8d8b389cbe2b91c8d5e29027fb45ced6bd560989) additional validation.

**Comment by ksm200** [comment]
I only have 1 custom plugin that uses sprite I will test with -heapsize 131072

**Comment by TheDoctor0** [comment]
> I only have 1 custom plugin that uses sprite

Mod pack on `csgo_cobblestone` is really close to 512 resource limit, so it may crash with this custom plugin and work without it.

> I will test with -heapsize 131072

Does `csgo_dust2_new` work now?

> L 08/25/2020 - 16:33:09: Info (map "csgo_dust2") (file "addons/amxmodx/logs/error_20200825.log")

L 08/25/2020 - 16:33:09: [HAMSANDWICH] Invalid entity 1
L 08/25/2020 - 16:33:09: [AMXX] Displaying debug trace (plugin "csgo_core.amxx", version "2.1.0")
L 08/25/2020 - 16:33:09: [AMXX] Run time error 10: native error (native "get_pdata_cbase")
L 08/25/2020 - 16:33:09: [AMXX] [0] csgo_core.sma::deploy_weapon_switch (line 2678)

Ok, we're getting closer. I [added](https://github.com/TheDoctor0/CSGOMod/commit/0cd5c54f9fb2e8e6b1ac5dbe2877acddec3bd459) more validation checks in all plugins to make `get_pdata_cbase` access crash impossible.

> L 08/25/2020 - 16:22:03: String formatted incorrectly - parameter 3 (total 2)
L 08/25/2020 - 16:22:03: [AMXX] Run time error 25 (plugin "csgo_accounts.amxx") - debug not enabled!
L 08/25/2020 - 16:22:03: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).

Probably fixed [here](https://github.com/TheDoctor0/CSGOMod/commit/e6bb585b3bf2f7bdb465d0f93734ab4e896235b1).

**Comment by ksm200** [comment]
https://www.sendspace.com/filegroup/SmRzjn2qkjezmwSBw2irEw
Demo 
0 animation in weapon

**Comment by TheDoctor0** [comment]
> 0 animation in weapon

[Fixed](https://github.com/TheDoctor0/CSGOMod/commit/6c7eba517f289c01df127bb554e23093a947ce00), in previous commit I added invalid ent check in update_client_data_post.

**Comment by TheDoctor0** [comment]
Were there any crashes on your server since this last fix?

**Comment by TheDoctor0** [comment]
I assume that this issue is no longer relevant.
@ksm200, you can reopen this issue or create a new one if you encounter any crashes.
