### ISSUE TITLE
[CS:GO] Query failed.

### ISSUE THREAD

**Issue by Damigeana** [TheDoctor0/CSGOMod#38]
L 08/29/2020 - 22:31:51: [CS:GO] Query failed. [1364] Field 'steamid' doesn't have a default value
L 08/29/2020 - 22:31:51: [CS:GO StatTrak] Query failed. [1364] Field 'steamid' doesn't have a default value

**Comment by Damigeana** [comment]
L 08/29/2020 - 22:33:37: [CS:GO] Query failed. [1364] Field 'name' doesn't have a default value
L 08/29/2020 - 22:33:37: [CS:GO StatTrak] Query failed. [1364] Field 'name' doesn't have a default value
L 08/29/2020 - 22:33:47: [CS:GO Accounts] Query failed. [1364] Field 'name' doesn't have a default value

**Comment by TheDoctor0** [comment]
It seems like your MySQL server is running in Strict SQL Mode as all columns are NULL by default if not specified otherwise.

**Comment by Damigeana** [comment]
Still same error

**Comment by TheDoctor0** [comment]
It's being tracked in #48.

**Comment by Damigeana** [comment]
https://i.gyazo.com/b5ce35329bd1e58f162b74a103f50af9.png

**Comment by TheDoctor0** [comment]
Fixed in version [2.1.1](https://github.com/TheDoctor0/CSGOMod/releases/tag/2.1.1).
If you suffer from this error use `csgo_reset_data` command or remove all tables manually as they need to be recreated.
