### ISSUE TITLE
Custom Stuff

### ISSUE THREAD

**Issue by Damigeana** [TheDoctor0/CSGOMod#4]
Can you make the starttrak for custom skins?
Can you add open case for dropping skins? "If can add a custom sprite for the open case. Like on zombie escape when you win or lose the round."
Can you make a contract for skins?
Can you add some agents?

PS. I have a plugin for crosshair i can give you the source if you want to integrate to your mode :P
PS2. Sorry for adding hear i think in email you said to add hear me "request". I think they are a good idea atleast some of them. :D

**Comment by NoahLTU** [comment]
Yeah actually it would be cool if you would add case opening system to 😃

**Comment by TheDoctor0** [comment]
> Can you make the starttrak for custom skins?
If you mean by that to track kills by skin not by weapon, it's certainly possible, 
but I don't know if it's worth it as it's really small addition to overall gameplay.

> Can you add open case for dropping skins?
Well, weapon skins draw is not really a case opening, but some effects can be added.

> Can you make a contract for skins?
It's not a first time that someone asks about it.
Contracts for skins can be done, but would it be really time consuming.
If someone want to do it, fork this repository and implement it.
I'll gladly accept the pull request with that feature.

> Can you add some agents?
I may use the Unprecacher module to replace player models with custom alternatives.
But I'll never introduce models that decrease visibility - as Valve did in CS:GO with some agents.

**Comment by Damigeana** [comment]
> > Can you make the starttrak for custom skins?
> 
> If you mean by that to track kills by skin not by weapon, it's certainly possible,
> but I don't know if it's worth it as it's really small addition to overall gameplay.
- Is a good thing becase you cand add more skins in the future. So is not gona be borring so every one will play more and make hours to have certains starttrak skins.
> 
> > Can you add open case for dropping skins?
> 
> Well, weapon skins draw is not really a case opening, but some effects can be added.
If you cand do that it gona be a realy good achiving.
> 
> > Can you make a contract for skins?
> 
> It's not a first time that someone asks about it.
> Contracts for skins can be done, but would it be really time consuming.
> If someone want to do it, fork this repository and implement it.
> I'll gladly accept the pull request with that feature.
I dont know somebody very good like you on scripting but i think we can sorted out this one.
We can make a donation fund to get this one done. I know maybe you work and dont have time for this.
We cant ask you to do more since you was making this one free.
I realy appreciate what you have done.
> > Can you add some agents?
> 
> I may use the Unprecacher module to replace player models with custom alternatives.
> But I'll never introduce models that decrease visibility - as Valve did in CS:GO with some agents.
You can do how you consider this one but will be good if we can change or add some models.

**Comment by TheDoctor0** [comment]
I created issues for all those ideas, so they can be tracked separately.

> We can make a donation fund to get this one done. I know maybe you work and dont have time for this.
We cant ask you to do more since you was making this one free.

I must say that I was thinking about a donation fund for further development of this mod for quite a while.
Yes, I have a full-time job as a software engineer and on top of that work as a freelancer,
so time that I can dedicate for open-source projects is really limited.

**Comment by Damigeana** [comment]
> I created issues for all those ideas, so they can be tracked separately.
> 
> > We can make a donation fund to get this one done. I know maybe you work and dont have time for this.
> > We cant ask you to do more since you was making this one free.
> 
> I must say that I was thinking about a donation fund for further development of this mod for quite a while.
> Yes, I have a full-time job as a software engineer and on top of that work as a freelancer,
> so time that I can dedicate for open-source projects is really limited.

I have more FUTURE PROOF ideas :)
