### ISSUE TITLE
csgo_cobblestone reaches the precache limit

### ISSUE THREAD

**Issue by regener** [TheDoctor0/CSGOMod#40]
>L 31/08/2020 - 09:35:01: (map "csgo_cobblestone") Host_Error: ED_ParseEdict: Model '*238' failed to precache because the item count is over the 512 limit.
> Reduce the number of brush models and/or regular models in the map to correct this.

I have the mod itself only on a fresh installed server, all other maps works yet.

Until a solution I think it should be removed from the maprotation list.

**Comment by TheDoctor0** [comment]
Are you sure about that?

![20200831175720_1](https://user-images.githubusercontent.com/16612504/91740351-7acab600-ebb3-11ea-9ac8-f40f20e5da0d.jpg)

Yes, csgo_cobblestone is really, really close to the precache limit, but it works if there are no additional plugins that add resources to precache.

**Comment by regener** [comment]
Can you check the 'rescount' command on csg_dust?

Here is mine with level changing to Cobble. (I cut out the admin login text)

> L 08/31/2020 - 18:36:50: -------- Mapchange to csgo_dust --------
> L 08/31/2020 - 18:36:54: [csgo_core.amxx] CS:GO Mod by O'Zone (v2.1.0).
> L 08/31/2020 - 18:36:54: [csgo_core.amxx] Loaded 1413 skins from 74 files.
> L 08/31/2020 - 18:39:05: [admincmd.amxx] Cmd: "Name<26><STEAM_0:1:XXXXXXXX><>" server console (cmdline "rescount")
> 
>   Type    : Total Limit
> 
>   model   : 414   510  
>   sound   : 323   511  
>   generic : 17    4096 
>   event   : 29    255  
>   decal   : 673   511  
> 
> 1456 Total of precached resource count
> 
> L 08/31/2020 - 18:39:19: [admincmd.amxx] Cmd: "Name<26><STEAM_0:1:XXXXXXXX><>" server console (cmdline "amx_map csgo_cobblestone")
> L 08/31/2020 - 18:39:19: [admincmd.amxx] Cmd: "ServerName<0><><>" changelevel "csgo_cobblestone"
> L 08/31/2020 - 18:39:21: -------- Mapchange to csgo_cobblestone --------
> L 08/31/2020 - 18:39:23: [csgo_core.amxx] CS:GO Mod by O'Zone (v2.1.0).
> L 08/31/2020 - 18:39:23: [csgo_core.amxx] Loaded 1413 skins from 74 files.
> Executing ReGameDLL Configuration File 
> Host_Error: ED_ParseEdict: Model '*238' failed to precache because the item count is over the 512 limit.
> Reduce the number of brush models and/or regular models in the map to correct this.
> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> Exe build: 10:14:22 Aug 19 2020 (2321)
> ... etc

Unprecacher's list.ini is the same as in this repo.

Plugins:
> L 08/31/2020 - 18:53:43: [admincmd.amxx] Cmd: "Name<8><STEAM_0:1:XXXXXXXX><>" server console (cmdline "amx_plugins")
> 
> Currently loaded plugins:
> 
> id  name                    version     author            url                              file         status   
> [  1] 0   Admin Base              1.10.0.540  AMXX Dev Team                                      admin.amxx   running  
> [  2] 1   Admin Commands          1.10.0.540  AMXX Dev Team                                      admincmd.am  running  
> [  3] 2   Admin Help              1.10.0.540  AMXX Dev Team                                      adminhelp.a  running  
> [  4] 3   Multi-Lingual System    1.10.0.540  AMXX Dev Team                                      multilingua  running  
> [  5] 4   Menus Front-End         1.10.0.540  AMXX Dev Team                                      menufront.a  running  
> [  6] 5   Commands Menu           1.10.0.540  AMXX Dev Team                                      cmdmenu.amx  running  
> [  7] 6   Players Menu            1.10.0.540  AMXX Dev Team                                      plmenu.amxx  running  
> [  8] 7   Maps Menu               1.10.0.540  AMXX Dev Team                                      mapsmenu.am  running  
> [  9] 8   Plugin Menu             1.10.0.540  AMXX Dev Team                                      pluginmenu.  running  
> [ 10] 9   Admin Chat              1.10.0.540  AMXX Dev Team                                      adminchat.a  running  
> [ 11] 10  Anti Flood              1.10.0.540  AMXX Dev Team                                      antiflood.a  running  
> [ 12] 11  Scrolling Message       1.10.0.540  AMXX Dev Team                                      scrollmsg.a  running  
> [ 13] 12  Info. Messages          1.10.0.540  AMXX Dev Team                                      imessage.am  running  
> [ 14] 13  Admin Votes             1.10.0.540  AMXX Dev Team                                      adminvote.a  running  
> [ 15] 14  NextMap                 1.10.0.540  AMXX Dev Team                                      nextmap.amx  running  
> [ 16] 15  Nextmap Chooser         1.10.0.540  AMXX Dev Team                                      mapchooser.  running  
> [ 17] 16  TimeLeft                1.10.0.540  AMXX Dev Team                                      timeleft.am  running  
> [ 18] 17  Pause Plugins           1.10.0.540  AMXX Dev Team                                      pausecfg.am  running  
> [ 19] 18  Stats Configuration     1.10.0.540  AMXX Dev Team                                      statscfg.am  running  
> [ 20] 19  Restrict Weapons        1.10.0.540  AMXX Dev Team                                      restmenu.am  running  
> [ 21] 20  StatsX                  1.10.0.540  AMXX Dev Team                                      statsx.amxx  running  
> [ 22] 21  CS Misc. Stats          1.10.0.540  AMXX Dev Team                                      miscstats.a  running  
> [ 23] 22  KGB Bots                2.31        Desikac & Ovidiu                                   csgo_specbo  running  
> [ 24] 23  Maxspeed API            1.0         Beast                                              maxspeed_ap  running  
> [ 25] 24  Fast Knife              1.0         Beast                                              fastknife.a  running  
> [ 26] 25  Multijump               1.0         serfreeman1337    unknown                          re_multijum  running  
> [ 27] 26  CS:GO Mod Core          2.1.0       O'Zone                                             csgo_core.a  running  
> [ 28] 27  CS:GO Clans             2.1.0       O'Zone                                             csgo_clans.  running  
> [ 29] 28  CS:GO Accounts          2.1.0       O'Zone                                             csgo_accoun  running  
> [ 30] 29  CS:GO Nades             2.1.0       O'Zone                                             csgo_nades.  running  
> [ 31] 30  CS:GO VIP and SVIP      2.1.0       O'Zone                                             csgo_vip_sv  running  
> [ 32] 31  CS:GO Server Menu       2.1.0       O'Zone                                             csgo_server  running  
> [ 33] 32  CS:GO Transfer          2.1.0       O'Zone                                             csgo_transf  running  
> [ 34] 33  CS:GO Operations        2.1.0       O'Zone                                             csgo_operat  running  
> [ 35] 34  CS:GO Molotov           2.1.0       DynamicBits & O'                                   csgo_moloto  running  
> [ 36] 35  CS:GO Smoke             2.1.0       Numb & O'Zone                                      csgo_smoke.  running  
> [ 37] 36  CS:GO Zeus              2.1.0       wopox1337 & O'Zo                                   csgo_zeus.a  running  
> [ 38] 37  CS:GO Run Boost         2.1.0       O'Zone                                             csgo_runboo  running  
> [ 39] 38  CS:GO Inspect           2.1.0       O'Zone                                             csgo_inspec  running  
> [ 40] 39  CS:GO Buy Menu          2.1.0       O'Zone                                             csgo_buymen  running  
> [ 41] 40  CS:GO Rank System       2.1.0       O'Zone                                             csgo_ranks.  running  
> [ 42] 41  CS:GO Assist and Reven  2.1.0       O'Zone                                             csgo_assist  running  
> [ 43] 42  CS:GO StatTrak          2.1.0       O'Zone                                             csgo_stattr  running  
> [ 44] 43  CS:GO No Distractions   2.1.0       O'Zone                                             csgo_no_dis  running  
> 
> 44 plugins, 44 running

I have 4 custom plugins only: specbots, multijump, a fast knife and a speed api for that. None of them requires precaching.

**Comment by TheDoctor0** [comment]
Sure:
```
L 08/31/2020 - 19:00:59: -------- Mapchange to csgo_dust --------
L 08/31/2020 - 19:01:01: [csgo_core.amxx] CS:GO Mod by O'Zone (v2.0.0).
L 08/31/2020 - 19:01:01: [csgo_core.amxx] Loaded 1413 skins from 74 files.
[AMXX] Loaded 2 admins from file
L 08/31/2020 - 19:01:01: Server cvar "amx_nextmap" = "csgo_dust"
[TheDoctor0 - Base Pack] Executing AMX Mod X Configuration File 
Scrolling message displaying frequency: 10:00 minutes
L 08/31/2020 - 19:01:02: Started map "csgo_dust" (CRC "-562008692")
> rescount

  Type    : Total Limit

  model   : 391   510  
  sound   : 128   511  
  generic : 17    4096 
  event   : 29    255  
  decal   : 225   511  
------------------------
790 Total of precached resource count
```
It's my test server with [BasePack](https://github.com/AMXX-pl/BasePack) and this mod.

**Comment by TheDoctor0** [comment]
I disabled unprecacher module and rescounts are exactly the same as yours, so maybe you skipped step 3 of [installation](https://github.com/TheDoctor0/CSGOMod#installation)?

**Comment by regener** [comment]
My bad, I had a typo in the metamod's plugins.ini thus the unprecacher wasn't even working.
Sorry.
