### ISSUE TITLE
Round MVP

### ISSUE THREAD

**Issue by TheDoctor0** [TheDoctor0/CSGOMod#41]
There is already a map MVP, but round MVP seems reasonable and may be a good addition.

Proposed by @DevilBoy-eXe in #34.

**Comment by TheDoctor0** [comment]
@ShadowsAdi send me a link to his [MVP of the Round](https://forums.alliedmods.net/showthread.php?t=327690) plugin.
I'll probably include it as a part of this mod after making some minor adjustements.

**Comment by popilas** [comment]
![desra](https://user-images.githubusercontent.com/74811825/104131693-bb67e680-5380-11eb-8e1a-ef0da5ed9cc6.png)
Its be 4 player but one leave when map change
The older version works well . In this version i see or gets one player or get server.

There is still a bug with molotov  (not critical - mean server dont crash)but as i have a record i will create a theme

**Comment by Mussano** [comment]
MVP of the round 'Name' [Kills 9 Including 4 HS] something like this will be nice if possible.
