### ISSUE TITLE
bug function?

### ISSUE THREAD

**Issue by tenlimba** [TheDoctor0/CSGOMod#50]
i have this bug on mod

09/04/2020 - 21:43:24: [AMXX] Plugin ("csgo_mod.amxx") is setting itself as failed.
09/04/2020 - 21:43:24: [AMXX] Plugin says: Function out of bounds. Got: 186 Max: 129

**Comment by TheDoctor0** [comment]
Can you enable debug mode for this plugin and then post error log?

**Comment by tenlimba** [comment]
I update mod but 
09/05/2020 - 09:41:13: [AMXX] Plugin ("csgo_core.amxx") is setting itself as failed.
09/05/2020 - 09:41:13: [AMXX] Plugin says: Function out of bounds. Got: 186 Max: 129
09/05/2020 - 09:41:13: [AMXX] Run time error 1 (plugin "csgo_core.amxx") - forced exit
09/05/2020 - 09:41:13: [AMXX] Plugin ("csgo_accounts.amxx") is setting itself as failed.
09/05/2020 - 09:41:13: [AMXX] Plugin says: Function out of bounds. Got: 187 Max: 129
09/05/2020 - 09:41:13: [AMXX] Run time error 1 (plugin "csgo_accounts.amxx") - forced exit

**Comment by TheDoctor0** [comment]
This is definitely a problem with Hamsandwich module, looking at those plugins I would say that `Ham_CS_Player_ResetMaxSpeed` hook is not available or not working properly for you.

1. Enable debug mode for both plugins - error will be more specific.
2. Show output of those commands:
- amxx version
- amxx modules

**Comment by tenlimba** [comment]
meta list:
Currently loaded plugins:
descriptionstat pend file verssrcload unlod
[ 1] Reunion RUN- reunion_mm_i386. v0.1.0.9 iniStart Never
[ 2] AMX Mod X RUN- amxmodx_mm_i386. v1.9.0.5 iniStart ANY
[ 3] LocalizeBug Fix RUN- localizebugfix_m v2.3iniStart Never
[ 4] ReAuthCheckRUN- reauthcheck_mm_i v0.1.6 iniStart Never
[ 5] hackdetector RUN- hackdetector_amx v0.15.32 iniANYANY
[ 6] Ultimate Unprec RUN- unprecacher_mm_i vBeta 2. iniChlvl Chlvl
[ 7] MySQRUN- mysql_amxx_i386. v1.8.2 pl2ANYANY
[ 8] Fun RUN- fun_amxx_i386.so v1.8.2 pl2ANYANY
[ 9] Engine RUN- engine_amxx_i386 v1.8.2 pl2ANYANY
[10] FakeMetaRUN- fakemeta_amxx_i3 v1.8.2 pl2ANYANY
[11] CStrike RUN- cstrike_amxx_i38 v1.9.0.5 pl2ANYANY
[12] CSX RUN- csx_amxx_i386.so v1.9.0.5 pl2ANYANY
[13] Ham Sandwich RUN- hamsandwich_amxx v1.8.2 pl2ANYANY
13 plugins, 13 running

console after restart
####### SERVICE RESTART AT 2020-09-05 16:02 BY CLIENT9657 #######

Enabling debug mode
Auto-restarting the server on crash

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
dlopen failed trying to load:
/home/client9657/.steam/sdk32/steamclient.so
with error:
/home/client9657/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 18:46:47 May 18 2020 (2228)
STEAM Auth Server
"fps_max" is "100.0"
Server IP address 93.114.82.47:27015
LoadLibrary failed on hu p#: hu p#: cannot open shared object file: No such file or directory

Metamod version 1.21p38 Copyright (c) 2001-2013 Will Day
Patch: Metamod-P (mm-p) v38 Copyright (c) 2004-2018 Jussi Kivilinna
Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `meta gpl' for details.


AMX Mod X version 1.9.0.5271 Copyright (c) 2004-2015 AMX Mod X Development Team
AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
This is free software and you are welcome to redistribute it under
certain conditions; type 'amxx gpl' for details.

09/05/2020 - 12:01:38: [GEOIP] Database info: GEO-106FREE 20080801 Build 1 Copyright (c) 2007 MaxMind LLC All Rights Reserved
stray key in process_key: item_getiteminfo 5000
[ReAuthCheck] Version: 0.1.6 Linux 'Counter-Strike 1.6'
[ReAuthCheck] Success: Configuration executed.
[ReAuthCheck] Success: Build ReHLDS version defined Linux '2228'
[HACKD] Found compatible ReHLDS engine.
09/05/2020 - 12:01:38: -------- Mapchange to de_dust2 --------
09/05/2020 - 12:01:39: [csgo_core.amxx] CS:GO Mod by O'Zone (v2.1.0).
09/05/2020 - 12:01:39: [csgo_core.amxx] Loaded 115 skins from 114 files.
[r4ge Guard] Detected original dproto(non r4ge)
[r4ge Guard] Detected dproto version 2
[r4ge Guard] Checking if r4ge-server-guard is first in plugins.ini : YES
[AMXX] Loaded 0 admins from file
09/05/2020 - 12:01:39: [AMXX] Plugin ("csgo_core.amxx") is setting itself as failed.
09/05/2020 - 12:01:39: [AMXX] Plugin says: Function out of bounds. Got: 186 Max: 129
09/05/2020 - 12:01:39: [AMXX] Displaying debug trace (plugin "csgo_core.amxx", version "2.1.0")
09/05/2020 - 12:01:39: [AMXX] Run time error 1: forced exit
09/05/2020 - 12:01:39: [AMXX] [0] hamsandwich.inc::__fatal_ham_error (line 436)
09/05/2020 - 12:01:39: [AMXX] Plugin ("csgo_accounts.amxx") is setting itself as failed.
09/05/2020 - 12:01:39: [AMXX] Plugin says: Function out of bounds. Got: 187 Max: 129
09/05/2020 - 12:01:39: [AMXX] Displaying debug trace (plugin "csgo_accounts.amxx", version "2.1.0")
09/05/2020 - 12:01:39: [AMXX] Run time error 1: forced exit
09/05/2020 - 12:01:39: [AMXX] [0] hamsandwich.inc::__fatal_ham_error (line 436)
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
dlopen failed trying to load:
/home/client9657/.steam/sdk32/steamclient.so
with error:
/home/client9657/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit

Executing AMX Mod X Configuration File
Scrolling message displaying frequency: 10:00 minutes
Executing AMX Mod X Configuration File
Scrolling message displaying frequency: 10:00 minutes
Menu item 17 added to Menus Front-End: "Plugin Cvars" from plugin "pluginmenu.amxx"
Menu item 18 added to Menus Front-End: "Plugin Commands" from plugin "pluginmenu.amxx"
09/05/2020 - 12:01:40: [CS:GO Clans] Init SQ Error: Can't connect to local MySQ server through socket '/tmp/mysql.sock' (2) (2002)
09/05/2020 - 12:01:40: [CS:GO Ranks] Init SQ Error: Can't connect to local MySQ server through socket '/tmp/mysql.sock' (2) (2002)
09/05/2020 - 12:01:40: [CS:GO StatTrak] Init SQ Error: Can't connect to local MySQ server through socket '/tmp/mysql.sock' (2) (2002)
Connection to Steam servers successful.
VAC secure mode is activated.
[r4ge Guard] Checking build versions

**Comment by TheDoctor0** [comment]
> [ 7] MySQRUN- mysql_amxx_i386. v1.8.2 pl2ANYANY
[ 8] Fun RUN- fun_amxx_i386.so v1.8.2 pl2ANYANY
[ 9] Engine RUN- engine_amxx_i386 v1.8.2 pl2ANYANY
[10] FakeMetaRUN- fakemeta_amxx_i3 v1.8.2 pl2ANYANY
[13] Ham Sandwich RUN- hamsandwich_amxx v1.8.2 pl2ANYANY

Well, no wonder there is a problem with this Hamsandwich hook.
You have mismatched versions of AMXX modules and some are from 1.8.2.
Upgrade all to 1.9.0.5271 as it is your AMXX version and this will solve this issue.
If you want you can upgrade to latest 1.10 version using [BasePack](https://github.com/AMXX-pl/BasePack).
