### ISSUE TITLE
All parts of a PRIMARY KEY must be NOT NULL

### ISSUE THREAD

**Issue by tenlimba** [TheDoctor0/CSGOMod#51]
how to resolve this error?
9/05/2020 - 12:44:57: [CS:GO Clans] Init SQ Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NUL in a key, use UNIQUE instead
09/05/2020 - 12:44:57: [CS:GO Clans] Init SQ Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NUL in a key, use UNIQUE instead
09/05/2020 - 12:44:57: [CS:GO Accounts] Init SQ Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NUL in a key, use UNIQUE instead
09/05/2020 - 12:44:57: [CS:GO Ranks] Init SQ Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NUL in a key, use UNIQUE instead
09/05/2020 - 12:44:57: [CS:GO Ranks] Init SQ Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NUL in a key, use UNIQUE instead
09/05/2020 - 12:44:57: [CS:GO StatTrak] Init SQ Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NUL in a key, use UNIQUE instead

I have 2.1.1 version.

**Comment by TheDoctor0** [comment]
Just checked it and MySQL 5.7+ does not support NULL values in primary keys anymore which was introduced as a fix for missing default values for name/steamid columns when running in SQL strict mode.

You can probably just use 2.1.0 if you want, but I'll fix this and release version 2.1.2 in ~30 minutes.
