### ISSUE TITLE
Pull request.

### ISSUE THREAD

**Issue by ShadowsAdi** [TheDoctor0/CSGOMod#52]
https://github.com/ShadowsAdi/CSGOMod/pull/1/files

**Comment by TheDoctor0** [comment]
You should make it here, not on your fork, as I cannot merge it from there.
When creating pull request use **compare across forks** option and select:
1. Base repository: `TheDoctor0/CSGOMod`; base: `master`.
2. Base repository: `ShadowsAdi/CSGOMod`; base: `your_branch_with_changes`.

Which will generate this url: https://github.com/TheDoctor0/CSGOMod/compare/master...ShadowsAdi:ShadowsAdi-patch-1
