### ISSUE TITLE
f1 autobuy CT + server crash

### ISSUE THREAD

**Issue by boriscois** [TheDoctor0/CSGOMod#58]
https://www.youtube.com/watch?v=3LCDUlkOSIo

FATAL ERROR (shutting down): PF_MessageBegin_I: with no target entity
Segmentation fault (core dumped)

**Comment by TheDoctor0** [comment]
Just tried it on my test server and I cannot replicate this issue.

Please post:
1. Content from `debug.log` if server is running with `-debug` parameter.
2. Output for those commands:
- `version`
- `meta version`
- `meta list`
- `amxx version`
- `amxx plugins`

**Comment by boriscois** [comment]
version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.7.0.693-dev
Build date: 18:20:58 Jan 28 2020 (2117)
Build from: https://github.com/dreamstalker/rehlds/commit/c4cecf5


meta version
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:54 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70



meta list
Currently loaded plugins:
description stat pend file vers src load unload
[ 1] Reunion RUN - reunion_mm_i386.so v0.1.0.92 ini Start Never
[ 2] ReAuthCheck RUN - reauthcheck_mm_i386.so v0.1.6 ini Start Never
[ 3] AMX Mod X RUN - amxmodx_mm_i386.so v1.8.3-dev+5201 ini Start ANY
[ 4] Ultimate Unprecacher RUN - unprecacher_mm_i386.so vBeta 2.5.3 ini Chlvl Chlvl
[ 5] FakeMeta RUN - fakemeta_amxx_i386.so v1.8.3-dev+5201 pl3 ANY ANY
[ 6] Ham Sandwich RUN - hamsandwich_amxx_i386.so v1.8.3-dev+5201 pl3 ANY ANY
[ 7] CStrike RUN - cstrike_amxx_i386.so v1.8.3-dev+5201 pl3 ANY ANY
[ 8] Engine RUN - engine_amxx_i386.so v1.8.3-dev+5201 pl3 ANY ANY
[ 9] MySQL RUN - mysql_amxx_i386.so v1.8.3-dev+5201 pl3 ANY ANY
[10] Fun RUN - fun_amxx_i386.so v1.8.3-dev+5201 pl3 ANY ANY
[11] CSX RUN - csx_amxx_i386.so v1.8.3-dev+5201 pl3 ANY ANY

amxx version
AMX Mod X 1.8.3-dev+5201 (http://www.amxmodx.org) and i try first time with 1.9 5271

[ 1] Admin Base 1.8.3-dev+ AMXX Dev Team admin.amxx running
[ 2] Admin Commands 1.8.3-dev+ AMXX Dev Team admincmd.amxx running
[ 3] Admin Help 1.8.3-dev+ AMXX Dev Team adminhelp.amxx running
[ 4] Slots Reservation 1.8.3-dev+ AMXX Dev Team adminslots.amxx running
[ 5] Multi-Lingual System 1.8.3-dev+ AMXX Dev Team multilingual.am running
[ 6] Menus Front-End 1.8.3-dev+ AMXX Dev Team menufront.amxx running
[ 7] Commands Menu 1.8.3-dev+ AMXX Dev Team cmdmenu.amxx running
[ 8] Players Menu 1.8.3-dev+ AMXX Dev Team plmenu.amxx running
[ 9] Maps Menu 1.8.3-dev+ AMXX Dev Team mapsmenu.amxx running
[ 10] Plugin Menu 1.8.3-dev+ AMXX Dev Team pluginmenu.amxx running
[ 11] Admin Chat 1.8.3-dev+ AMXX Dev Team adminchat.amxx running
[ 12] Anti Flood 1.8.3-dev+ AMXX Dev Team antiflood.amxx running
[ 13] Scrolling Message 1.8.3-dev+ AMXX Dev Team scrollmsg.amxx running
[ 14] Info. Messages 1.8.3-dev+ AMXX Dev Team imessage.amxx running
[ 15] Admin Votes 1.8.3-dev+ AMXX Dev Team adminvote.amxx running
[ 16] NextMap 1.8.3-dev+ AMXX Dev Team nextmap.amxx running
[ 17] Nextmap Chooser 1.8.3-dev+ AMXX Dev Team mapchooser.amxx running
[ 18] TimeLeft 1.8.3-dev+ AMXX Dev Team timeleft.amxx running
[ 19] Pause Plugins 1.8.3-dev+ AMXX Dev Team pausecfg.amxx running
[ 20] Stats Configuration 1.8.3-dev+ AMXX Dev Team statscfg.amxx running
[ 21] CS:GO Mod Core 2.1.0 O'Zone csgo_core.amxx running
[ 22] CS:GO Clans 2.1.0 O'Zone csgo_clans.amxx running
[ 23] CS:GO Accounts 2.1.0 O'Zone csgo_accounts.a running
[ 24] CS:GO Nades 2.1.0 O'Zone csgo_nades.amxx running
[ 25] CS:GO VIP and SVIP 2.1.0 O'Zone csgo_vip_svip.a running
[ 26] CS:GO Server Menu 2.1.0 O'Zone csgo_server_men running
[ 27] CS:GO Transfer 2.1.0 O'Zone csgo_transfer.a running
[ 28] CS:GO Operations 2.1.0 O'Zone csgo_operations running
[ 29] CS:GO Molotov 2.1.0 DynamicBits & O' csgo_molotov.am running
[ 30] CS:GO Smoke 2.1.0 Numb & O'Zone csgo_smoke.amxx running
[ 31] CS:GO Zeus 2.1.0 wopox1337 & O'Zo csgo_zeus.amxx running
[ 32] CS:GO Run Boost 2.1.0 O'Zone csgo_runboost.a running
[ 33] CS:GO Inspect 2.1.0 O'Zone csgo_inspect.am running
[ 34] CS:GO Buy Menu 2.1.0 O'Zone csgo_buymenu.am running
[ 35] CS:GO Rank System 2.1.0 O'Zone csgo_ranks.amxx running
[ 36] CS:GO Assist and Reven 2.1.0 O'Zone csgo_assist_rev running
[ 37] CS:GO StatTrak 2.1.0 O'Zone csgo_stattrak.a running
[ 38] CS:GO No Distractions 2.1.0 O'Zone csgo_no_distrac running

**Comment by TheDoctor0** [comment]
Okay, I don't see any additional modules or plugins, so it's definitely not it.

1. I assume that you tried autobuy with all mod plugins disabled an it works fine?

2. Do you have to to reinstall the server, upload [BasePack](https://github.com/AMXX-pl/BasePack) and then CS:GO mod?
If the crash would not occur anymore it would mean that it was caused by AMXX/Metamod/ReHLDS/ReGameDLL.
