### ISSUE TITLE
Server shutdown

### ISSUE THREAD

**Issue by LycaNiaNN** [TheDoctor0/CSGOMod#59]
L 09/09/2020 - 21:44:38: FATAL ERROR (shutting down): SV_ModelIndex: SV_ModelIndex: model models/csgo_ozone/galil/v_galil.mdl not precached
FATAL ERROR (shutting down): SV_ModelIndex: SV_ModelIndex: model models/csgo_ozone/galil/v_galil.mdl not precached
./hlds_run: line 255:  2972 Segmentation fault      $HL_CMD

**Comment by TheDoctor0** [comment]
Default CS 1.6 models are replaced with CS:GO models using Unprecacher module.

Make sure that `models/csgo_ozone/galil/v_galil.mdl` model in uploaded to you server, 
because this error clearly suggests that it is not to be found.

**Comment by LycaNiaNN** [comment]
It`s done, it was a problem from me.
