### ISSUE TITLE
spam in server console

### ISSUE THREAD

**Issue by boriscois** [TheDoctor0/CSGOMod#60]
when I run it spams this in the server console, then if I press shift it stops spamming

SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step1.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step1.wav not precached (0)
SV_BuildSoundMsg: player/pl_step4.wav not precached (0)
SV_BuildSoundMsg: player/pl_step3.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step3.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step1.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step3.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step3.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step1.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step3.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step1.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step3.wav not precached (0)
SV_BuildSoundMsg: player/pl_step2.wav not precached (0)
SV_BuildSoundMsg: player/pl_step1.wav not precached (0)

**Comment by TheDoctor0** [comment]
It's a side effect caused by client-size sounds that were removed from precache.
Players of course can here those sounds as they should, so there is no change in gameplay in any way.
