### ISSUE TITLE
steamid sql

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#61]
L 09/12/2020 - 14:49:31: Log file started (file "cstrike/addons/amxmodx/logs/csgo-error.log") (game "cstrike") (amx "1.9.0.5271")
L 09/12/2020 - 14:49:31: [CS:GO] Query failed. [1054] Unknown column 'steamid' in 'field list'
L 09/12/2020 - 14:49:36: [CS:GO Ranks] Query failed. [1054] Unknown column 'steamid' in 'field list'

**Comment by TheDoctor0** [comment]
If you updated from 2.0.x to 2.1.x it is required to remove tables from database as configurable [save type](https://github.com/TheDoctor0/CSGOMod/issues/29) was added.
You can use `csgo_reset_data` command.

**Comment by ksm200** [comment]
But then I lose the backup of the old server

**Comment by TheDoctor0** [comment]
In that case you may add `steamid VARCHAR(35)` field manually to `csgo_ranks`, `csgo_hud`, `csgo_accounts`, `csgo_clans_applications`, `csgo_clans_members`, `csgo_clans_applications`, `csgo_skins` and `csgo_data` tables.
