### ISSUE TITLE
erro with users my server

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#62]
![WhatsApp Image 2020-09-12 at 12 44 41](https://user-images.githubusercontent.com/64114407/92999277-01f22500-f4f6-11ea-9184-b9cc8ce006b2.jpeg)

Link with video crashed cs my friend
https://www.sendspace.com/file/vjvanw

**Comment by TheDoctor0** [comment]
That error suggest that you do not have enough RAM or disk space on your server.
It's not related to the mod itself at all.
