### ISSUE TITLE
new logs error

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#63]
L 09/12/2020 - 15:35:08: Start of error session.
L 09/12/2020 - 15:35:08: Info (map "csgo_dust2") (file "addons/amxmodx/logs/error_20200912.log")
L 09/12/2020 - 15:35:08: Invalid index 1788156 (count: 1413)
L 09/12/2020 - 15:35:08: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/12/2020 - 15:35:08: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:08: Unhandled dynamic native error
L 09/12/2020 - 15:35:08: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/12/2020 - 15:35:08: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:09: Invalid index 1788156 (count: 1413)
L 09/12/2020 - 15:35:09: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/12/2020 - 15:35:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:09: Unhandled dynamic native error
L 09/12/2020 - 15:35:09: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/12/2020 - 15:35:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:11: Invalid index 1788156 (count: 1413)
L 09/12/2020 - 15:35:11: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/12/2020 - 15:35:11: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:11: Unhandled dynamic native error
L 09/12/2020 - 15:35:11: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/12/2020 - 15:35:11: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:12: Invalid index 1788156 (count: 1413)
L 09/12/2020 - 15:35:12: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/12/2020 - 15:35:12: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:12: Unhandled dynamic native error
L 09/12/2020 - 15:35:12: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/12/2020 - 15:35:12: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:12: Invalid index 1788156 (count: 1413)
L 09/12/2020 - 15:35:12: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/12/2020 - 15:35:12: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:12: Unhandled dynamic native error
L 09/12/2020 - 15:35:12: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/12/2020 - 15:35:12: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:13: Invalid index 1788156 (count: 1413)
L 09/12/2020 - 15:35:13: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/12/2020 - 15:35:13: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:13: Unhandled dynamic native error
L 09/12/2020 - 15:35:13: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/12/2020 - 15:35:13: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:14: Invalid index 1788156 (count: 1413)
L 09/12/2020 - 15:35:14: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/12/2020 - 15:35:14: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:14: Unhandled dynamic native error
L 09/12/2020 - 15:35:14: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/12/2020 - 15:35:14: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:48:16: String formatted incorrectly - parameter 3 (total 2)
L 09/12/2020 - 15:48:16: [AMXX] Run time error 25 (plugin "csgo_accounts.amxx") - debug not enabled!
L 09/12/2020 - 15:48:16: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:50:09: [FUN] Invalid player 2
L 09/12/2020 - 15:50:09: [AMXX] Run time error 10 (plugin "csgo_accounts.amxx") (native "set_user_maxspeed") - debug not enabled!
L 09/12/2020 - 15:50:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:50:09: [FUN] Invalid player 2
L 09/12/2020 - 15:50:09: [AMXX] Run time error 10 (plugin "csgo_accounts.amxx") (native "set_user_maxspeed") - debug not enabled!
L 09/12/2020 - 15:50:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:50:09: [FUN] Invalid player 2
L 09/12/2020 - 15:50:09: [AMXX] Run time error 10 (plugin "csgo_accounts.amxx") (native "set_user_maxspeed") - debug not enabled!
L 09/12/2020 - 15:50:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:50:09: [FUN] Invalid player 2
L 09/12/2020 - 15:50:09: [AMXX] Run time error 10 (plugin "csgo_accounts.amxx") (native "set_user_maxspeed") - debug not enabled!
L 09/12/2020 - 15:50:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:50:09: [HAMSANDWICH] Invalid entity (2)
L 09/12/2020 - 15:50:09: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ExecuteHamB") - debug not enabled!
L 09/12/2020 - 15:50:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).

**Comment by TheDoctor0** [comment]
Post output for those commands:
1. `version`
2. `meta version`
3. `meta list`
4. `amxx version`
5. `amxx plugins`

**Comment by ksm200** [comment]
Version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.7.0.698-dev
Build date: 10:14:22 Aug 19 2020 (2321)
Build from: https://github.com/dreamstalker/rehlds/commit/376bc15

Meta VersioN
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:54 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70

Meta List
Currently loaded plugins:
      description           stat pend  file                       vers             src  load  unload
 [ 1] Reunion               RUN   -    reunion_mm_i386.so         v0.1.0.135       ini  Start Never
 [ 2] WHBlocker             RUN   -    whblocker_mm_i386.so       v1.5.697         ini  Chlvl ANY  
 [ 3] AMX Mod X             RUN   -    amxmodx_mm_i386.so         v1.9.0.5271      ini  Start ANY  
 [ 4] Print Center Fix      RUN   -    printcenterfix_mm_i386.so  v1.0.1           ini  ANY   Never
 [ 5] Ultimate Unprecacher  RUN   -    unprecacher_mm_i386.so     vBeta 2.5.3      ini  Chlvl Chlvl
 [ 6] VoiceTranscoder       RUN   -    vtc.so                     v2017RC5         ini  ANY   ANY  
 [ 7] Fun                   RUN   -    fun_amxx_i386.so           v1.9.0.5271      pl3  ANY   ANY  
 [ 8] Engine                RUN   -    engine_amxx_i386.so        v1.9.0.5271      pl3  ANY   ANY  
 [ 9] FakeMeta              RUN   -    fakemeta_amxx_i386.so      v1.9.0.5271      pl3  ANY   ANY  
 [10] GeoIP                 RUN   -    geoip_amxx_i386.so         v1.9.0.5271      pl3  ANY   ANY  
 [11] CStrike               RUN   -    cstrike_amxx_i386.so       v1.9.0.5271      pl3  ANY   ANY  
X[12] CSX                   RUN   -    csx_amxx_i386.so           v1.9.0.5271      pl3  ANY   ANY   [13] Ham Sandwich          RUN   -    hamsandwich_amxx_i386.so   v1.9.0.5271      pl3  ANY   ANY  
 [14] ReAPI                 RUN   -    reapi_amxx_i386.so         v5.15.0.197-dev  pl3  ANY   Never
 [15] MySQL                 RUN   -    mysql_amxx_i386.so         v1.9.0.5271      pl3  ANY   ANY  

amxx Version
AMX Mod X 1.9.0.5271 (http://www.amxmodx.org)
Authors:
	David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
	Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
	Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
	Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Jun 24 2020 13:53:30
Built from: https://github.com/alliedmodders/amxmodx/commit/5eea3e5
Build ID: 5271:5eea3e5
Core mode: JIT+ASM32

amxx pluginns Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Base              1.9.0.5271  AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.9.0.5271  AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.9.0.5271  AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.9.0.5271  AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.9.0.5271  AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.9.0.5271  AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.9.0.5271  AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.9.0.5271  AMXX Dev Team     plmenu.amxx      running  
 [  9] Teleport Menu           1.9.0.5271  AMXX Dev Team     telemenu.amxx    running  
 [ 10] Maps Menu               1.9.0.5271  AMXX Dev Team     mapsmenu.amxx    running  
 [ 11] Plugin Menu             1.9.0.5271  AMXX Dev Team     pluginmenu.amxx  running  
 [ 12] Admin Chat              1.9.0.5271  AMXX Dev Team     adminchat.amxx   running  
 [ 13] Anti Flood              1.9.0.5271  AMXX Dev Team     antiflood.amxx   running  
X[ 14] Admin Votes             1.9.0.5271  AMXX Dev Team     adminvote.amxx   running   [ 15] NextMap                 1.9.0.5271  AMXX Dev Team     nextmap.amxx     running  
 [ 16] Nextmap Chooser         1.9.0.5271  AMXX Dev Team     mapchooser.amxx  running  
 [ 17] TimeLeft                1.9.0.5271  AMXX Dev Team     timeleft.amxx    running  
 [ 18] Pause Plugins           1.9.0.5271  AMXX Dev Team     pausecfg.amxx    running  
 [ 19] Stats Configuration     1.9.0.5271  AMXX Dev Team     statscfg.amxx    running  
 [ 20] CS:GO Mod Core          2.1.0       duh-              csgo_core.amxx   debug    
 [ 21] CS:GO Clans             2.1.3       O'Zone            csgo_clans.amxx  running  
 [ 22] CS:GO Accounts          2.1.3       O'Zone            csgo_accounts.a  debug    
 [ 23] CS:GO Nades             2.1.3       O'Zone            csgo_nades.amxx  running  
 [ 24] CS:GO VIP and SVIP      2.1.3       O'Zone            csgo_vip_svip.a  running  
 [ 25] CS:GO Server Menu       2.1.0       O'Zone            csgo_server_men  running  
 [ 26] CS:GO Transfer          2.1.3       O'Zone            csgo_transfer.a  running  
 [ 27] CS:GO Operations        2.1.3       O'Zone            csgo_operations  running  
 [ 28] CS:GO Molotov           2.1.3       DynamicBits & O'  csgo_molotov.am  running  
X[ 29] CS:GO Smoke             2.1.3       Numb & O'Zone     csgo_smoke.amxx  running   [ 30] CS:GO Zeus              2.1.3       wopox1337 & O'Zo  csgo_zeus.amxx   running  
 [ 31] CS:GO Run Boost         2.1.3       O'Zone            csgo_runboost.a  running  
 [ 32] CS:GO Inspect           2.1.3       O'Zone            csgo_inspect.am  running  
 [ 33] CS:GO Buy Menu          2.1.3       O'Zone            csgo_buymenu.am  paused   
 [ 34] CS:GO Rank System       2.1.3       O'Zone            csgo_ranks.amxx  running  
 [ 35] CS:GO Assist and Reven  2.1.3       O'Zone            csgo_assist_rev  running  
 [ 36] CS:GO StatTrak          2.1.3       O'Zone            csgo_stattrak.a  running  
 [ 37] CS:GO No Distractions   2.1.3       O'Zone            csgo_no_distrac  running  
37 plugins, 36 running

**Comment by Damigeana** [comment]
I get the same error sometime.

**Comment by TheDoctor0** [comment]
@ksm200, it seems that you have mixed versions of plugins - core plugin and buymenu from 2.1.0 and rest of plugins from 2.1.3.
Correct this, enable `debug` mode for `csgo_core.amxx`, `csgo_accounts.amxx` and `csgo_buymenu.amxx` and if those errors will occur again please post logs again (they will be more detailed).

**Comment by TheDoctor0** [comment]
```
L 09/12/2020 - 15:35:08: Info (map "csgo_dust2") (file "addons/amxmodx/logs/error_20200912.log")
L 09/12/2020 - 15:35:08: Invalid index 1788156 (count: 1413)
L 09/12/2020 - 15:35:08: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/12/2020 - 15:35:08: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:35:08: Unhandled dynamic native error
L 09/12/2020 - 15:35:08: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
```
This error has been fixed in [this commit](https://github.com/TheDoctor0/CSGOMod/commit/bd65ab1f19e73a1aff95ee6cd3515e18445b573a). 
It is kinda weird, because this error was introduced with [multilang support](https://github.com/TheDoctor0/CSGOMod/commit/dbf69f4a4b83cc71bc54b909da584be5501e8936) nearly a month ago and no one noticed.

```
L 09/12/2020 - 15:50:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:50:09: [FUN] Invalid player 2
L 09/12/2020 - 15:50:09: [AMXX] Run time error 10 (plugin "csgo_accounts.amxx") (native "set_user_maxspeed") - debug not enabled!
L 09/12/2020 - 15:50:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:50:09: [HAMSANDWICH] Invalid entity (2)
L 09/12/2020 - 15:50:09: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ExecuteHamB") - debug not enabled!
L 09/12/2020 - 15:50:09: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
```
Those errors should not be possible in the first place. In both cases there is `is_user_alive` check.
But nevertheless I [added](https://github.com/TheDoctor0/CSGOMod/commit/5f1cbde0eba2f21c6eb6215d13a25bde5223b0c9) `is_user_valid` checks just to be sure.

```
L 09/12/2020 - 15:35:14: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/12/2020 - 15:48:16: String formatted incorrectly - parameter 3 (total 2)
L 09/12/2020 - 15:48:16: [AMXX] Run time error 25 (plugin "csgo_accounts.amxx") - debug not enabled!
```
Fixed in [this commit](https://github.com/TheDoctor0/CSGOMod/commit/e7b845a63ffd9b73b093ea2b8c8ea523c96b1b1a).

It seems like that's all, so I'm closing this issue and I'll release version 2.1.4.
If you find more errors, open new issue 👍
