### ISSUE TITLE
new errors.

### ISSUE THREAD

**Issue by LucijasO** [TheDoctor0/CSGOMod#64]
Hey, is this some kind of a new bug?

L 09/13/2020 - 13:51:22: Info (map "csgo_cache") (file "addons/amxmodx/logs/error_20200913.log")
L 09/13/2020 - 13:51:22: Invalid index 1812261 (count: 185)
L 09/13/2020 - 13:51:22: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/13/2020 - 13:51:22: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/13/2020 - 13:51:22: Unhandled dynamic native error
L 09/13/2020 - 13:51:22: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/13/2020 - 13:51:22: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/13/2020 - 13:51:23: Invalid index 1812261 (count: 185)
L 09/13/2020 - 13:51:23: [AMXX] Run time error 10 (plugin "csgo_core.amxx") (native "ArrayGetArray") - debug not enabled!
L 09/13/2020 - 13:51:23: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
L 09/13/2020 - 13:51:23: Unhandled dynamic native error
L 09/13/2020 - 13:51:23: [AMXX] Run time error 10 (plugin "csgo_buymenu.amxx") (native "csgo_get_skin_name") - debug not enabled!
L 09/13/2020 - 13:51:23: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).

**Comment by TheDoctor0** [comment]
Already tracked in #63.
