### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by LycaNiaNN** [TheDoctor0/CSGOMod#66]
L 09/15/2020 - 20:53:11: Called dynanative into a paused plugin.
L 09/15/2020 - 20:53:11: [AMXX] Displaying debug trace (plugin "csgo_ranks.amxx", version "2.1.4")
L 09/15/2020 - 20:53:11: [AMXX] Run time error 10: native error (native "csgo_get_current_skin_name")
L 09/15/2020 - 20:53:11: [AMXX]    [0] csgo_ranks.sma::display_hud (line 499)

**Comment by LycaNiaNN** [comment]
I think it`s a bug from Draw, try to go to Draw and press 1, after that you will understand.

**Comment by TheDoctor0** [comment]
> I think it`s a bug from Draw, try to go to Draw and press 1, after that you will understand.

Well, for me nothing happens. Skins drawing works as expected.

**Comment by LycaNiaNN** [comment]
Ok, and why i have errors?
On what dev do you test(amxmodx), because all i have it`s up to date ...

**Comment by TheDoctor0** [comment]
I use [BasePack](https://github.com/AMXX-pl/BasePack) on my test server.
There may be some bug, but it's probably harder to replicate that just drawing a skin.

**Comment by TheDoctor0** [comment]
It may have been fixed in [this commit](https://github.com/TheDoctor0/CSGOMod/commit/6c342b67ddb79251966eb362127ec50eaeba5a1c) that is included [2.1.5](https://github.com/TheDoctor0/CSGOMod/releases/tag/2.1.5) release. Can you confirm that?
