### ISSUE TITLE
shotgun xm bug - crash server / buymenu bug

### ISSUE THREAD

**Issue by boriscois** [TheDoctor0/CSGOMod#68]
FATAL ERROR (shutting down): PF_MessageBegin_I: with no target entity
Segmentation fault (core dumped)

video : https://www.youtube.com/watch?v=M_gE6EZusE4

+++++ bug buy handguns and rifle from menu

 09/16/2020 - 07:04:13: Invalid index 1113346 (count: 10)
L 09/16/2020 - 07:04:13: [AMXX] Displaying debug trace (plugin "csgo_core.amxx", version "2.1.3")
L 09/16/2020 - 07:04:13: [AMXX] Run time error 10: native error (native "ArrayGetArray")
L 09/16/2020 - 07:04:13: [AMXX] [0] csgo_core.sma::get_skin_info (line 3457)
L 09/16/2020 - 07:04:13: [AMXX] [1] csgo_core.sma::_csgo_get_skin_name (line 3160)
L 09/16/2020 - 07:04:13: Unhandled dynamic native error
L 09/16/2020 - 07:04:13: [AMXX] Displaying debug trace (plugin "csgo_buymenu.amxx", version "2.1.3")
L 09/16/2020 - 07:04:13: [AMXX] Run time error 10: native error (native "csgo_get_skin_name")
L 09/16/2020 - 07:04:13: [AMXX] [0] csgo_buymenu.sma::clcmd_rifle (line 348)
L 09/16/2020 - 07:04:13: [AMXX] [1] csgo_buymenu.sma::clcmd_buy_handle (line 119)
L 09/16/2020 - 07:04:14: Invalid index 1113346 (count: 10)

**Comment by TheDoctor0** [comment]
Error with buymenu was fixed in [2.1.4](https://github.com/TheDoctor0/CSGOMod/releases/tag/2.1.4).

Crash on shotgun reload has been reported in #67.
