### ISSUE TITLE
Bug? #2

### ISSUE THREAD

**Issue by LucijasO** [TheDoctor0/CSGOMod#69]
Hey again ^-^.
So today i was playing a map with my friend where there were some hostages (It was cs_max). And when I took the hostages they just disappeared and it crashed my server in the next round. Does it have anything to do with the mod or smth?

**Comment by TheDoctor0** [comment]
That's most certainly an issue caused by sounds removed by unprecacher similar to #68.
I'll check it on some hostage map.

**Comment by LucijasO** [comment]
Okay
