### ISSUE TITLE
Add exclusive/special skin type

### ISSUE THREAD

**Issue by Zetz512** [TheDoctor0/CSGOMod#70]
hello!
you can add a new config in csgo skins ini about to show or hide a skin only from skin shop? 
a example, come christmas and u can buy x skins that doesnt show before, if u bought it now is it in your inventory forever even if that skin is hide again after x event end...

cheers, amazing work! keep it up

**Comment by TheDoctor0** [comment]
Interesting concept!
Also, it would be quite trivial to implement.

**Comment by TheDoctor0** [comment]
After some consideration, it may be also a good opportunity to introduce command and native for adding skins.
This will allow to make some skins really exclusive and not available to buy/draw with Euro at any point.
