### ISSUE TITLE
Add an option to save the player's password into setinfo automatically upon register

### ISSUE THREAD

**Issue by regener** [TheDoctor0/CSGOMod#72]
Add an option to the register menu (with Yes/No switch) to automatically set the password into the player's config file (for the auto login). This way they don't have to manually enter it, since many of them doesn't do it and they complain after. 😄

**Comment by TheDoctor0** [comment]
This is already being done [automatically](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_accounts.sma#L428).
Good chunk of players use read-only config, so it's even saved to second config (`csgopass.cfg` by default).
Of course for some Non-Steam clients with built-in protectors it may not work and players have to save password manually.

**Comment by regener** [comment]
Somehow I missed that.
Also I have Steam with cl_filterstuffcmd 0 and I don't have the csgopass.cfg
