### ISSUE TITLE
Allow text chat between spectator and T/CT team

### ISSUE THREAD

**Issue by regener** [TheDoctor0/CSGOMod#74]
In the current state the spectator can only read T/CT messages, but they can't see what the spec writes.

As I have seen you have hooked the chat in 3 plugins: Clans, Ranks and the VIP plugin.
I wanted to edit it to allow the players to read Spec message, but I don't know how to start it.
My other plugins do hook the full chat and output using client_print_color, but your method is different.

**Comment by TheDoctor0** [comment]
`SayText msgid` hook should handle spectators as well.
What method do you use in other plugins?

**Comment by regener** [comment]
I'm not sure if it is better or not, but hooking the say and say_team command themselves, then getting the message (read_args) and altering it if needed, and finally client_print_color with for loops.

I am not good in coding, so I'm sure my way is overcomplicated 😅

But it is still a fact that alive players can't see the Spectators message, I have tested that with players on both sides (I was Spec then we switched, I was an alive player).

**Comment by TheDoctor0** [comment]
In CS 1.6 alive players should only see messages from other alive players in their team by default.
By hooking into say/say_team commands you probably bypass those chat settings - so it's actually a bug.

**Comment by regener** [comment]
Yes, I think of that as a feature. 😃
I will close this Issue now.

Btw, can I contact you somewhere like Steam?

**Comment by TheDoctor0** [comment]
https://steamcommunity.com/id/dw0/
