### ISSUE TITLE
Idea: Include some kind of physics plugin

### ISSUE THREAD

**Issue by regener** [TheDoctor0/CSGOMod#75]
Like in CSS and CSGO you could shoot armory items on the ground or move them by grenade explosion.

Examples:
https://forums.alliedmods.net/showthread.php?t=66472
https://forums.alliedmods.net/showthread.php?t=194880?t=194880

**Comment by TheDoctor0** [comment]
From those two plugins, I would select Weapon Physics as I used it a few times in the past.
It is quite outdated, so would require a rewrite, but nevertheless, it seems like a good idea.

**Comment by Zetz512** [comment]
sorry to comment a closed thread but you have the weapon physics made in reapi, u can found out at dev-cs.ru

**Comment by regener** [comment]
I don't see any reason to switch to reapi, afaik nothing else needs reapi atm in this mod. That would limit the mod to rehlds+regamedll servers and that is a bad idea.
Also if you prefer reapi then you can switch it for yourself.

**Comment by Zetz512** [comment]
i mean, the reapi versión is a remake of that plugin so.. i think its more optimized and the only issues are c4 and grenade has physics what is so bad ingame, thats it

**Comment by TheDoctor0** [comment]
Sooner or later ReAPI will be introduced as a dependency for this mod, but I don't think that it's worth it for such a minor plugin.
