### ISSUE TITLE
Improve hud info

### ISSUE THREAD

**Issue by Zetz512** [TheDoctor0/CSGOMod#80]
Only show gametime/euro/rank on roundend/freezetime/changemap(mp_chattime)
Or add cvar for when you want to show that info

Change skin name position to above of money hud and the Statrak stats above of skin name
Add a info of kills u has in the actually round
Like 3 points u can put with ASCII and if are more than 3 kills change these points for X kills (ex: 4x and up) on the ammo side

Sry for my bad english
ty for answer

**Comment by TheDoctor0** [comment]
HUD only shows info that is necessary for players and I don't think that any changes are necessary.

> Change skin name position to above of money hud and the Statrak stats above of skin name
> Add a info of kills u has in the actually round
> Like 3 points u can put with ASCII and if are more than 3 kills change these points for X kills (ex: 4x and up) on the ammo side

That's an external plugin that you can [download](https://forums.alliedmods.net/showthread.php?p=30598) by yourself.
