### ISSUE TITLE
Crash with p_* models

### ISSUE THREAD

**Issue by Zetz512** [TheDoctor0/CSGOMod#83]
Its kinda weird because it happens rarely...

In case of p_flashbang.mdl, sometimes works or failed in crash... 

I think the cause of that crash can be for fps server when are playing so many players in it... Anyways idk how unprecacher works but here is the sys_error.log content recently from a server with latest rehlds, regamedll and metamod-p38 version.

ty for advance

 ``L02/11/2020 - 17:37:11: (map "csgo_assault") SV_ModelIndex: SV_ModelIndex: model models/p_deagle.mdl not precached

L 02/11/2020 - 17:52:03: (map "de_dust2") SV_ModelIndex: SV_ModelIndex: model models/p_deagle.mdl not precachedL 02/11/2020 - 17:55:14: (map "csgo_assault") SV_ModelIndex: SV_ModelIndex: model models/p_usp.mdl not precached
L 02/11/2020 - 18:25:59: (map "csgo_hell") SV_ModelIndex: SV_ModelIndex: model models/p_deagle.mdl not precached

L 02/11/2020 - 18:30:51: (map "csgo_assault") SV_ModelIndex: SV_ModelIndex: model models/p_knife.mdl not precached
L 02/11/2020 - 19:37:09: (map "csgo_aztec") SV_ModelIndex: SV_ModelIndex: model models/p_usp.mdl not precached

L 02/11/2020 - 19:38:50: (map "csgo_assault") SV_ModelIndex: SV_ModelIndex: model models/p_knife.mdl not precached

L 02/11/2020 - 19:45:14: (map "csgo_assault") SV_ModelIndex: SV_ModelIndex: model models/p_flashbang.mdl not precached

L 02/11/2020 - 20:09:06: (map "csgo_kabul") SV_ModelIndex: SV_ModelIndex: model models/p_c4.mdl not precached``

Off: i cant donate you from paypal...
I think its due with the Argentina economy right now ;/

**Comment by TheDoctor0** [comment]
From what I know, unprecacher module replaces model paths on server start, so more players on server should not be an issue.
If you want, you can for now just remove p_* models from [unprecacher config](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/unprecacher/list.ini).

**Comment by Zetz512** [comment]
Now crash with v_* models what i "already" remove from unprecacher list 

I will figure it out disabling some plugins what can be the cause of sv crashes
