### ISSUE TITLE
Command for toggling hud

### ISSUE THREAD

**Issue by Happy2906** [TheDoctor0/CSGOMod#85]
It would be great if you could add - 

- Command to turn off cs go skins so you can play with normal 1.6 models - Increases FPS
- Command to turn off hud completely. It also increases FPS.

Thanks

**Comment by TheDoctor0** [comment]
I don't think it makes sense to allow disabling skins on a mod where skins are its core part.
If someone doesn't want skins, they will not play on this kind of mod.

As for HUD, that's a valid suggestion 👍

**Comment by Happy2906** [comment]
>I don't think it makes sense to allow disabling skins on a mod where skins are its core part.
See, the thing is that some people play just to get as much skins as they can, and some people play because of the community and their friends etc. I own a server with your first edition of CS:GO mod for almost a year, and I can tell you from my own experience that 40-50% people don't play with skins, including myself of course. Please, if you get a chance, just go onto couple of servers that has your mod installed and you will be surprised how many people are actually using cs 1.6 skins. 

I have opened a server for other players, not for myself and after good 10 months I know what players on my servers want, and do not want. Of course, it's your choice what you'll going to do, this is just a little advice. Your CS:GO mod rocks anyway 💯 

Thanks, have a great day.

**Comment by popilas** [comment]
This i need too , deflaut skins on or off its be nice. I see one server use this.

**Comment by TheDoctor0** [comment]
If that's really the case then ok. I'll make a second issue to track hud and skins switching separately.

**Comment by popilas** [comment]
> If that's really the case then ok. I'll make a second issue to track hud and skins switching separately.

I play one server who have this who use your mod and i wanna it to!!! :)

**Comment by popilas** [comment]
Like this
[https://dev-cs.ru/attachments/24713/](url)

**Comment by TheDoctor0** [comment]
This was available on my mod before version 2.0.
Right now skins are handled in a much more complicated way, so adding this option is not as simple as it was previously.

**Comment by popilas** [comment]
> This was available on my mod before version 2.0.
> Right now skins are handled in a much more complicated way, so adding this option is not as simple as it was previously.

can you add link?

**Comment by TheDoctor0** [comment]
It's available in the past releases: [1.4](https://github.com/TheDoctor0/CSGOMod/releases/tag/1.4).

**Comment by popilas** [comment]
> It's available in the past releases: [1.4](https://github.com/TheDoctor0/CSGOMod/releases/tag/1.4).

hmm, maybe can you add to csgo_core.sma? if no I will try self.. thanks.

**Comment by TheDoctor0** [comment]
I'll try to implement this before releasing version 2.3.0 this weekend, but I can't promise that it will be included in this version.

**Comment by popilas** [comment]
oh its be will nice!! please

**Comment by TheDoctor0** [comment]
@popilas both hud and skins toggling have been added, so you just have to wait till Sunday for the new release.

**Comment by popilas** [comment]
Thanks!!! I love you :D

**Comment by popilas** [comment]
Hey, thanks for update! i updated skins on off works, But i mean lke this orginal skins
https://www11.zippyshare.com/v/zWqK9OBX/file.html

**Comment by TheDoctor0** [comment]
If you want to vanilla cs:go skins you need to remove them from [unprecacher config](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/unprecacher/list.ini).
This module is used to replace base models and it's not possible to allow players to disable them on demand.

**Comment by popilas** [comment]
> If you want to vanilla cs:go skins you need to remove them from [unprecacher config](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/unprecacher/list.ini).
> This module is used to replace base models and it's not possible to allow players to disable them on demand.

but its posible to do like ON/OFF? two server with you csgomod have it

**Comment by TheDoctor0** [comment]
I have plans to merge default cs:go skins into model files with submodels to reduce the number of files that players have to download. When it will be done, skins toggling would change them between cs:go and cs 1.6 without any additional changes.

But until then, you need to remove them from unprecacher config.
Then you can add those models back to the core plugin just as it was made in version [1.x.](https://github.com/TheDoctor0/CSGOMod/blob/1.4/csgo_mod.sma) - look at _defaultSkins_ usage.

**Comment by TheDoctor0** [comment]
> but its posible to do like ON/OFF? two server with you csgomod have it

I have plans to merge default cs:go skins into model files with submodels to reduce the number of files that players have to download. When it will be done, skins toggling would change them between cs:go and cs 1.6 without any additional changes.

But until then, you need to remove them from unprecacher config.
Then you can add those models back to the core plugin just as it was made in version 1.x. - look at defaultSkins usage.

**Comment by popilas** [comment]
Yes your csgo_mod1.4 have this choose and i wanna it to 2.3.0 maybe can you help me with add to 2.3.0 version? Thanks.

**Comment by popilas** [comment]
I try do it but got problems..

**Comment by TheDoctor0** [comment]
I'll probably make those changes to skins this week, so if you can't add it to the core plugin based on 1.x version, just wait a few days.

**Comment by popilas** [comment]
I wanna add to core plugin in 2.3.0 your version but i got some problems ... ;//

**Comment by popilas** [comment]
> I'll probably make those changes to skins this week, so if you can't add it to the core plugin based on 1.x version, just wait a few days.


maybe you can tell which day? thank you

**Comment by TheDoctor0** [comment]
Some of the required work has been already made - [compiler script](https://github.com/TheDoctor0/CSGOMod/blob/master/skins/compile.py).
Now I need to update skin textures filenames, make minor changes in core plugin, change unprecacher configuration, and write documentation about skin compilation.
I may finish it this week, but I have a lot of work (paid job), so you just have to be patient.

**Comment by popilas** [comment]
> Some of the required work has been already made - [compiler script](https://github.com/TheDoctor0/CSGOMod/blob/master/skins/compile.py).
> Now I need to update skin textures filenames, make minor changes in core plugin, change unprecacher configuration, and write documentation about skin compilation.
> I may finish it this week, but I have a lot of work (paid job), so you just have to be patient.

okey thanks. I will wait. good luck for you :)

**Comment by popilas** [comment]
Hello, how are you? 
maybe one can expect it today?

**Comment by TheDoctor0** [comment]
Unfortunately, I didn't have time on Saturday or Sunday, so I'll try to finish and release it in coming days.

**Comment by popilas** [comment]
okey, very waiting, thanks!

**Comment by popilas** [comment]
> Unfortunately, I didn't have time on Saturday or Sunday, so I'll try to finish and release it in coming days.

Ok, very waiting, maybe you finish tomorrow? :) :+1:

**Comment by popilas** [comment]
Ok, very waiting, maybe you finish tomorrow? :) +1

**Comment by TheDoctor0** [comment]
Well, if not Cyberpunk 2077 I would have finished it 😄 
Despite that, I made some progress and now I only have to write documentation for skins compilation.

**Comment by popilas** [comment]
> Well, if not Cyberpunk 2077 I would have finished it 
> Despite that, I made some progress and now I only have to write documentation for skins compilation.

THanks! i will try Saturday, 
i see an update a few hours ago

**Comment by popilas** [comment]
I go problme wiht m3 model
FATAL ERROR (shutting down): SV_ModelIndex: SV_ModelIndex: model models/csgo_ozone_v2/m3/v_m3_0.mdl not precached

**Comment by TheDoctor0** [comment]
> I go problme wiht m3 model
> FATAL ERROR (shutting down): SV_ModelIndex: SV_ModelIndex: model models/csgo_ozone_v2/m3/v_m3_0.mdl not precached

Yup, that's possible as I didn't test the latest changes yet. I move the discussion about those skins changed to https://github.com/TheDoctor0/CSGOMod/issues/98.

**Comment by popilas** [comment]
maybe can you help only with defaultSkins usage.? I wanna do it from 1.4 to 2.3 version only this .. :/
