### ISSUE TITLE
csgo_core | Defaults Models list

### ISSUE THREAD

**Issue by Zetz512** [TheDoctor0/CSGOMod#88]
After disabling unprecacher module i still get crashes with message about some models are not precached like "models/csgo_ozone/galil/v_galil.mdl"

And i check out from csgo_core at defaultModels[]  see some models have the csgo_ozone/weapon/v_*.mdl on path

**Comment by TheDoctor0** [comment]
In the core plugin only hardcoded cs 1.6 default models are used.
"models/csgo_ozone/galil/v_galil.mdl" is default cs:go skin and it's only processed by unprecacher.
