### ISSUE TITLE
Mystery box

### ISSUE THREAD

**Issue by tenlimba** [TheDoctor0/CSGOMod#91]
You can't add a mystery box for euro and skins.
Here is a plugin you can be inspired by : https://forums.alliedmods.net/showthread.php?t=300976

**Comment by TheDoctor0** [comment]
Hi @tenlimba.
That would be a good addition if mystery boxes were also present in CS:GO.
I'm trying to keep this mod as close to CS:GO as possible, so I won't add it here.

However, if you want to use it with this mod on your server, go-ahead 😄

**Comment by tenlimba** [comment]
But can you help me make some changes to give you skins when you open a box?

**Comment by TheDoctor0** [comment]
To be honest, right now I have so much work that I don't have time.
