### ISSUE TITLE
save password /savepass ?

### ISSUE THREAD

**Issue by popilas** [TheDoctor0/CSGOMod#92]
Hello maybe can do like /savepass? or /savepassword . should not wirte setinfo _csgopass ..
Thanks !

**Comment by TheDoctor0** [comment]
The _setinfo "_csgopass"_ is only used for auto-login and that's the only acceptable way to save password in user files.

**Comment by popilas** [comment]
Rly? Like this?
register_clcmd("say /savepass", "SavePassword");
register_concmd("UserPassword", "PlayerPassword");
csgo_password_field = register_cvar("csgo_password_field", "_csgopass");
Password[id] = "";


public SavePassword(id)
{
	if(!Loged[id])
	{
		if(!gRegistered[id])
		{
			client_print_color(id, print_team_default, "%L", LANG_PLAYER, "NEED_REGISTER_1", Prefix);
			client_print_color(id, print_team_default, "%L", LANG_PLAYER, "NEED_REGISTER_2", Prefix);
			} else {
			client_print_color(id, print_team_default, "%L", LANG_PLAYER, "LOGIN_FIRST", Prefix);
		}
		return PLUGIN_HANDLED;
	}
	
	new passfield[32]; get_pcvar_string(csgo_password_field, passfield, 31);
	set_user_info(id, passfield, SavedPassword[id]);
	client_cmd(id, "setinfo %s %s", passfield, SavedPassword[id]); 
	
	client_print_color(id, print_team_default, "%L", LANG_PLAYER, "SUCCESS_SAVED", Prefix);
	
	return PLUGIN_HANDLED;
}



I tihnk its possible.
