### ISSUE TITLE
Molotov, Crash my server

### ISSUE THREAD

**Issue by talnaim2323** [TheDoctor0/CSGOMod#96]
Hi, first need to say
nice job and greate mod for CS 1.6

i have JB server and i like the molotov plugin so im take it and i connected to my mod.
the problem i see
when players are spawning while molotov burns and round restarts when fire is on the server will crash, this issue happens in empty server without any additional plugins can you fix it please

its happen even with clean amxx no any plugins except  from base of amxx..

AMXX 1.9.0
REHLDS + ReGameDLL
ReauthCheck
ReChecker
Reunion
revoice
SafeNameAndChat
whblocker

all of them are most new release.

if u can answer here
or discord/steam if u want..
https://steamcommunity.com/id/Mangekyou-Sharingan1
Mangekyou Sharingan#2309

**Comment by TheDoctor0** [comment]
Hello @talnaim2323.
Can you enable debug mode (_-debug_ in starting options) and post a full crash log?
That would help in pinpointing what really causes this issue.

**Comment by talnaim2323** [comment]
> Hello @talnaim2323.
> Can you enable debug mode (_-debug_ in starting options) and post a full crash log?
> That would help in pinpointing what really causes this issue.


Already use -debug but nothing..
dont have any logs or error when the server crash
Maybe its something with remove entity i dont know..

**Comment by TheDoctor0** [comment]
If you have `-debug` every single crash should be logged to `debug.log` (outside `cstrike` directory).
Without crash logs it's really hard to fix that kind of issue.

**Comment by talnaim2323** [comment]
> If you have `-debug` every single crash should be logged to `debug.log` (outside `cstrike` directory).
> Without crash logs it's really hard to fix that kind of issue.

Know about that but its show only the  info in
command line
i dont know why, maybe has problem with my server about that..

**Comment by talnaim2323** [comment]
> If you have `-debug` every single crash should be logged to `debug.log` (outside `cstrike` directory).
> Without crash logs it's really hard to fix that kind of issue.

ok man, in my another server its show log

`[New LWP 25113]
[New LWP 25121]
[New LWP 25130]
[New LWP 25123]
[New LWP 25127]
[New LWP 25128]
[New LWP 25129]
[New LWP 25141]
[New LWP 25120]
[New LWP 25196]
Core was generated by `./hlds_linux -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip 185.'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000 in ?? ()
No symbol table info available.
No shared libraries loaded at this time.
Stack level 0, frame at 0xffdb9bd0:
 eip = 0x0; saved eip End of crash report
----------------------------------------------`

**Comment by talnaim2323** [comment]
```
./hlds_run: line 255: 25113 Segmentation fault      (core dumped) $HL_CMD
BFD: Warning: /home2/cs16_clubs/cs-20001/core.25113 is truncated: expected core file size >= 154329088, found: 3014656.
Cannot access memory at address 0xf77628e8
Cannot access memory at address 0xf77628e4
Failed to read a valid object file image from memory.
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0xffdb9bcc: 
Cannot access memory at address 0xf77628e8
Cannot access memory at address 0xf77628e4
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffdb9bcc
email debug.log to linux@valvesoftware.com
Sun Dec 13 14:57:51 IST 2020: Server restart in 10 seconds
```

in console

**Comment by TheDoctor0** [comment]
Are you sure that molotov plugin is causing this? Those logs do not indicate that issue is connected to a plugin.
If you have a possibility, install [BasePack](https://github.com/AMXX-pl/BasePack) on a clean server, add nothing more than molotov plugin and test it.

**Comment by talnaim2323** [comment]
> Are you sure that molotov plugin is causing this? Those logs do not indicate that issue is connected to a plugin.
> If you have a possibility, install [BasePack](https://github.com/AMXX-pl/BasePack) on a clean server, add nothing more than molotov plugin and test it.

i will try it, not sure if i can..

**Comment by talnaim2323** [comment]
> Are you sure that molotov plugin is causing this? Those logs do not indicate that issue is connected to a plugin.
> If you have a possibility, install [BasePack](https://github.com/AMXX-pl/BasePack) on a clean server, add nothing more than molotov plugin and test it.

i will check with another server with ur `BasePack` same problem...
Unfortunately I do not have access to this server for commands line so dont have `-debug`
but in visual same problem.

try to throw few times molotov + smother with smoke
kill ur self and waiting to next round

try to do it and u see the server will borken..

**Comment by TheDoctor0** [comment]
I tried to throw some smokes and molotovs, then use the `kill` command but no crash.

Can you write step by step instruction to consistently cause a crash or record a video?
That would definitely help in further debugging.

**Comment by talnaim2323** [comment]
> I tried to throw some smokes and molotovs, then use the `kill` command but no crash.
> 
> Can you write step by step instruction to consistently cause a crash or record a video?
> That would definitely help in further debugging.

i will send u video later, its better if we move to steam/discord and ill show you..

tried with your BasePack
also with my its same all from `dev-cs` just amxx 1.9.0

**Comment by talnaim2323** [comment]
https://youtu.be/J7jpxdA8mPs


https://youtu.be/iJlyjV8lttA



2 tests
in the short video im even dont use kill/restart commands...

**Comment by TheDoctor0** [comment]
So it's not really that easy to replicate if you need to throw molotovs/smokes for like 2 minutes.

I made some minor changes to [the plugin](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_molotov.sma).
Testing this version on my server I have thrown dozens of smoke and molotovs without any crashes.
So if there will be any further problems on your server that's probably because of some modifications that you made.

**Comment by talnaim2323** [comment]
> So it's not really that easy to replicate if you need to throw molotovs/smokes for like 2 minutes.
> 
> I made some minor changes to [the plugin](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_molotov.sma).
> Testing this version on my server I have thrown dozens of smoke and molotovs without any crashes.
> So if there will be any further problems on your server that's probably because of some modifications that you made.

no im taking for test ur clean/original plugin.
and u can see in the video its not  crash by fixed time
in first video after 30-40 seconds
when im throw just 1-2 molotov 

and in second video 1-2 minutes
I intentionally did one after the other to  expedite the game
if in normal game its take more time but its happen im just do it more faster..
and thanks! i will try ur new plugin..

**Comment by talnaim2323** [comment]
xD in the first time im tried the new plugin just one smoke one molotov and crash
without restart/kill or something...

https://www.youtube.com/watch?v=97P_LeCj5Ig&ab_channel=CSSERVERS

also has warning in compiler: `Warning: Symbol is never used: "i" on line 409`

**Comment by TheDoctor0** [comment]
I was like: no way, that's impossible.
But I disabled every plugin except molotov and sure enough, a crash just after a few throws.

I analyzed this video as well as those that you send previously and I noticed that crashes occurred on weapon deploy.
Knowing that I could quite consistently cause a crash by spamming the molotov buy command when throwing it.

After some more debugging I was pretty sure that the problem is caused by some kind of race condition here:
```
new weapon = get_pdata_cbase(id, OFFSET_ACTIVE_ITEM, OFFSET_PLAYER_LINUX);
ExecuteHamB(Ham_Item_Deploy, weapon);
```
I removed it and additionally for some safety changed pev_valid usage across all the plugins.
Now it seems to be finally stable 🆗

**Comment by talnaim2323** [comment]
> I removed it and additionally for some safety changed pev_valid usage across all the plugins.
> Now it seems to be finally [stable ](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_molotov.sma)🆗

thanks i will check it, hope its be ok :)

**Comment by talnaim2323** [comment]
> I was like: no way, that's impossible.
> But I disabled every plugin except molotov and sure enough, a crash just after a few throws.
> 
> I analyzed this video as well as those that you send previously and I noticed that crashes occurred on weapon deploy.
> Knowing that I could quite consistently cause a crash by spamming the molotov buy command when throwing it.
> 
> After some more debugging I was pretty sure that the problem is caused by some kind of race condition here:
> 
> ```
> new weapon = get_pdata_cbase(id, OFFSET_ACTIVE_ITEM, OFFSET_PLAYER_LINUX);
> ExecuteHamB(Ham_Item_Deploy, weapon);
> ```
> 
> I removed it and additionally for some safety changed pev_valid usage across all the plugins.
> Now it seems to be finally [stable ](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_molotov.sma)🆗

still crashes...
same like before.

**Comment by TheDoctor0** [comment]
Can you try to replicate it on my test server?
**46.29.21.219:27540** (password: **test**)
Default access flags are set to "abcdefghijklmnopqrstuvxyz", so you can use any commands.

**Comment by talnaim2323** [comment]
> Can you try to replicate it on my test server?
> **46.29.21.219:27540** (password: **test**)
> Default access flags are set to "abcdefghijklmnopqrstuvxyz", so you can use any commands.
> I also disabled buyzone, time and money restriction for molotov for easier testing, and added smoke when buying it.

unfortunately it's still crashing also in your server..
im taked 2 video
1) molotov with smoke its crash so fast xD  [video1](https://youtu.be/nk5q7bmWbyw)
2) only molotov and with sv_restart 1 to restart round and made spawns [video 2](https://youtu.be/c837s3-Al-M)

**Comment by TheDoctor0** [comment]
That crash after multiple round restarts is interesting,
but to be honest that is the weirdest bug that I encountered in AMXX.
It's like looking for a needle in a haystack.

I made multiple changes to the plugin, you can test it out again if you want.

**Comment by talnaim2323** [comment]
> That crash after multiple round restarts is interesting,
> but to be honest that is the weirdest bug that I encountered in AMXX.
> It's like looking for a needle in a haystack.
> 
> I made multiple changes to the plugin, you can test it out again if you want.


in the first checking i did it fast but i will try later to do more tests, the **smoke** problem still crash the server

the **round restart** problem its looking like you fixed it  , but to be sure i will test it later more times..

**Comment by TheDoctor0** [comment]
Good that some progress has been made because it was starting to be infuriating for me.

Ok, so it's pretty clear that something is wrong with molotov extinguishing.
That is some really peculiar issue for the engine as crash logs stack show GetWeaponData in ReGameDLL.
I'll try to make some time in the evening and debug it further in order to fix it.

**Comment by talnaim2323** [comment]
> Good that some progress has been made because it was starting to be infuriating for me.
> 
> Ok, so it's pretty clear that something is wrong with molotov extinguishing.
> That is some really peculiar issue for the engine as crash logs stack show GetWeaponData in ReGameDLL.
> I'll try to make some time in the evening and debug it further in order to fix it.


yeah xD

to be sure the problem not related to **ReHLDS/ReGameDLL**
 i checked with **HLDS** server also with **REHLDS** without **ReGameDLL**
still crash with smoke..

**Comment by talnaim2323** [comment]
dont know if its help you
i forgot to tell you about that
but with more players the crash problem take more time

it's strange because alone its crash so fast most times i check after 1-2 molotov and smoke and its enough to crash the server.
Good Luck to slove this problem , waiting for new version...

**Comment by talnaim2323** [comment]
thank you for fixing the issue, i also got another plugin with the same problem that entity removal crashes the server could you please tell me how you got it fixed?

**Comment by TheDoctor0** [comment]
You can analyze the changes made [here ](https://github.com/TheDoctor0/CSGOMod/commit/6e97e82e3e13f3050b8c31e434f76f4a9f920c98).
In general, seems like that kind of entities must use think logic not tasks and need to be killed with `set_pev(ent, pev_flags, pev(entFire, pev_flags) | FL_KILLME);`.

**Comment by popilas** [comment]
Hello, server crash with new update .when i throw molotov when round end server crash not always but often I added two video:
https://www39.zippyshare.com/v/9dXL4LNe/file.html
https://www51.zippyshare.com/v/csMwhtLi/file.html

**Comment by TheDoctor0** [comment]
Thanks @popilas for reporting this.
That's probably caused by [this line](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_molotov.sma#L317). I made a separate issue https://github.com/TheDoctor0/CSGOMod/issues/102.

**Comment by popilas** [comment]
Can you tell me when you fix in this comm? Or i need try to define this line?

**Comment by TheDoctor0** [comment]
I want to fix it before releasing next version this weekend.

**Comment by talnaim2323** [comment]
> Can you tell me when you fix in this comm? Or i need try to define this line?

good to know im not check it on live server

> I want to fix it before releasing next version this weekend.

waiting for new release
thanks

**Comment by popilas** [comment]
> I want to fix it before releasing next version this weekend.

And can you add to new version whis from 1.4 version
Minimum graczy na serwerze do zdobywania euro
The minimum number of players on the server to earn Euros?
because now the players planting bomb when server players are  1 or 2 , and earn euros.

**Comment by TheDoctor0** [comment]
It's still available and even have been reworked by @regener [some time ago](https://github.com/TheDoctor0/CSGOMod/pull/82).
Check `csgo_min_players` and `csgo_min_player_filter` cvars.

Also, please do not ask questions in already closed issues that are not even related to the topic of the issue itself.
If you want to ask about something else, create a new issue.
