### ISSUE TITLE
Rework skins management

### ISSUE THREAD

**Issue by TheDoctor0** [TheDoctor0/CSGOMod#98]
- Merge default cs:go models with skin models
- Implement universal script to compile models with selected skins and generate _csgo_skins.ini_

**Comment by popilas** [comment]
Nice updates i see.. When release 2.4 ? :D nice

**Comment by TheDoctor0** [comment]
Soon, but I need to still fix a crash issue with [molotov extinguishing](https://github.com/TheDoctor0/CSGOMod/issues/96).

**Comment by popilas** [comment]
maybe you can do it in a few days, thanks

**Comment by popilas** [comment]
maybe you can do it in a few days, thanks , I think with molotov can do limit one each round

**Comment by TheDoctor0** [comment]
Nades are limited only by buy-time both in CS 1.6 and CS:GO, so I don't think that's a good idea.

**Comment by popilas** [comment]
> Nades are limited only by buy-time both in CS 1.6 and CS:GO, so I don't think that's a good idea.

but in video he buy 2 time molotov

**Comment by TheDoctor0** [comment]
It's only for testing purposes. Normally it doesn't work that way.

**Comment by popilas** [comment]
okey. i played one week with molotov about 10 players but no crashed. Waiting goods to 2.4 version. now server locked. Good luck after this i donate you. - You good.

**Comment by popilas** [comment]
Hello , when i delete P228 skins from csgo_skins.ini , and go to the server when skins are disabled its work fine with simple 1.6 gun, but when enable skins and you use p228 server crash and say:
SV_ModelIndex: SV_ModelIndex: model models/csgo_ozone_v2/p228/v_p228_0.mdl not precached

**Comment by popilas** [comment]
Hello, when i delete all your skins from csgo_skins.ini and i wanna add own skins not sub-models 
Like:
"Bayonet | Black Laminate"    "models/csgo_ozone/knife/v_bayoblacklaminate.mdl"           "0" "350"  "1" "1"
When skins enable server crash with log
SV_ModelIndex: SV_ModelIndex: model models/csgo_ozone_v2/knife/v_knife_0.mdl not precached
:/

**Comment by TheDoctor0** [comment]
New skins management has not been yet tested by me, that's why this issue is still open.

**Comment by popilas** [comment]
oh. okey. i just need make from 1.4 version csgo_mod.sma to do 2.3 version csgo_core do 
new const defaultModels  for deflaut to csgo skins..

**Comment by popilas** [comment]
How I can fix this in 2.4 version 
Skins Enabled
SV_ModelIndex: model models/csgo_ozone_v2/m249/v_m249_0.mdl not precached
SV_ModelIndex: model models/csgo_ozone_v2/m3/v_m3_0.mdl not precached
SV_ModelIndex: model models/csgo_ozone_v2/sg552/v_sg552_0.mdl not precached

**Comment by TheDoctor0** [comment]
Set newly added `csgo_default_skins` cvar to **0**.

**Comment by popilas** [comment]
> Set newly added `csgo_default_skins` cvar to **0**.

I do it
bind_pcvar_num(create_cvar("csgo_default_skins", "0"), defaultSkins);
But problems still are
model models/csgo_ozone_v2/m249/v_m249_0.mdl not precached

**Comment by TheDoctor0** [comment]
Set it in `csgo_mod.cfg` and use `amx_cvar csgo_default_skins` command to check the value.
It should work fine:
![20201228191027_1](https://user-images.githubusercontent.com/16612504/103234637-75526200-4940-11eb-9a5a-22124de2a7b3.jpg)

**Comment by popilas** [comment]
Ok but i wanna fix this with csgo_default_skins 1 ......
When i go to csgo_skins.ini and add
"Orginal"		"models/csgo_ozone_v2/m249/v_m249_0.md.mdl"
When work. But i wanna delete all csgo_skins.ini and add self skins, 
one word Then you delete sample " v_knife_0 or v_awp_0 " i mean sub models server crash with error  not precached.

**Comment by TheDoctor0** [comment]
Default cs:go models have been merged with skin models (first submodel in the first model).
It's impossible to use `csgo_default_skins "1"` if you want to remove _v_{weapon}_0.mdl_ models.

Skin management has been described in detail in [this instruction](https://github.com/TheDoctor0/CSGOMod#skins).
If you want to remove all skins for any weapon then remove all `.bmp` files from `skins` directory and recompile skins.

**Comment by popilas** [comment]
that’s all i wanted, but the easiest way for me is version 1.4... ech

**Comment by TheDoctor0** [comment]
To be honest, right now I don't even know what are you trying to achieve.
Previously you said that you don't want to have default cs:go skins and now you don't want to disable them by `csgo_default_skins` cvar - which is pretty much exactly like it worked in version 1.4.
With default skins disabled you can remove everything from `csgo_skins.ini` and add any models that you want.

**Comment by popilas** [comment]
if saying i want everything that is like version 1.4 but with 2.4 updates.
No i say i wanna deflaut skins and csgo skin only delfaut not skins. Ech never mind i try fix but im poor in scripting. 
What  i want like 1.4 mod.
if i fail i will use it  1.4 and I will need to translate it into English.

**Comment by TheDoctor0** [comment]
Well, if you would be more specific from the beginning I would not have wasted a lot of time.
I added the ability to disable submodels support (#100) by [uncommenting a flag](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_core.sma#L30), so it will work the same as in 1.4.

This is not included in the release yet, so you need to [download the whole repository](https://github.com/TheDoctor0/CSGOMod/archive/master.zip). 
Remember to upload a new models directory and Unprecacher list to your server. 
Of course, you also need to compile core plugin by yourself after uncommenting this new flag.
